{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "course-header",
   "metadata": {},
   "source": [
    "# Module 4: Planning and Goal Decomposition\n",
    "*Building Agents That Can Plan and Execute Complex Strategies*\n",
    "\n",
    "**Learning Objectives:**\n",
    "- Implement hierarchical planning systems for complex goals\n",
    "- Create agents that can break down goals into actionable steps\n",
    "- Build self-correcting and adaptive planning mechanisms\n",
    "- Design goal decomposition strategies for different problem types\n",
    "\n",
    "**Duration:** 60 minutes\n",
    "\n",
    "**Prerequisites:** Modules 1-3 (Foundations, Memory, Tool Integration)\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "planning-introduction",
   "metadata": {},
   "source": [
    "## 🎯 Why Planning Matters for Agents\n",
    "\n",
    "Up to this point, we've built agents that can reason, remember, and use tools. But **truly autonomous agents need sophisticated planning abilities** to:\n",
    "\n",
    "### 🧭 Navigate Complex Goal Spaces\n",
    "Real-world tasks aren't simple one-step operations. They require:\n",
    "- **Decomposition**: Breaking large goals into manageable subtasks\n",
    "- **Sequencing**: Determining the optimal order of operations\n",
    "- **Dependency Management**: Understanding what must happen before what\n",
    "- **Resource Allocation**: Planning within constraints of time, tools, and capabilities\n",
    "\n",
    "### 🔄 Adapt to Changing Conditions\n",
    "Plans must be dynamic and responsive:\n",
    "- **Monitoring**: Continuously assess progress and environment\n",
    "- **Replanning**: Adjust strategy when conditions change\n",
    "- **Error Recovery**: Handle failures and find alternative paths\n",
    "- **Optimization**: Improve plans based on new information\n",
    "\n",
    "### 🎪 Coordinate Multiple Objectives\n",
    "Advanced agents must balance competing goals:\n",
    "- **Priority Management**: Handle urgent vs. important tasks\n",
    "- **Resource Conflicts**: Resolve competing demands for tools/time\n",
    "- **Deadline Constraints**: Meet temporal requirements\n",
    "- **Quality vs. Speed**: Make appropriate trade-offs\n",
    "\n",
    "---\n",
    "\n",
    "## 🏗️ Planning Architecture Overview\n",
    "\n",
    "Modern agent planning systems use a hierarchical approach:\n",
    "\n",
    "```\n",
    "┌─────────────────────────────────────┐\n",
    "│        Strategic Planning           │ ← High-level goals\n",
    "├─────────────────────────────────────┤\n",
    "│        Tactical Planning            │ ← Mid-level objectives  \n",
    "├─────────────────────────────────────┤\n",
    "│       Operational Planning          │ ← Specific actions\n",
    "├─────────────────────────────────────┤\n",
    "│       Execution Monitoring          │ ← Progress tracking\n",
    "├─────────────────────────────────────┤\n",
    "│       Replanning & Adaptation       │ ← Dynamic adjustment\n",
    "└─────────────────────────────────────┘\n",
    "```\n",
    "\n",
    "### Planning Algorithms We'll Implement:\n",
    "1. **Hierarchical Task Networks (HTN)**: Top-down decomposition\n",
    "2. **Goal-Oriented Action Planning (GOAP)**: Bottom-up search\n",
    "3. **Monte Carlo Tree Search (MCTS)**: Probabilistic planning\n",
    "4. **Reactive Planning**: Real-time adaptation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "setup-imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Enhanced imports for planning systems\n",
    "import openai\n",
    "import json\n",
    "import time\n",
    "import asyncio\n",
    "import networkx as nx\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "from datetime import datetime, timedelta\n",
    "from typing import List, Dict, Any, Optional, Union, Tuple, Set\n",
    "from dataclasses import dataclass, field\n",
    "from enum import Enum\n",
    "from abc import ABC, abstractmethod\n",
    "import uuid\n",
    "import heapq\n",
    "import random\n",
    "import math\n",
    "from collections import defaultdict, deque\n",
    "import logging\n",
    "from pathlib import Path\n",
    "import copy\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Load environment\n",
    "load_dotenv()\n",
    "\n",
    "# Setup logging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# Helper functions\n",
    "def print_section(title: str, content: str):\n",
    "    \"\"\"Enhanced section formatter\"\"\"\n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"🎯 {title}\")\n",
    "    print(f\"{'='*60}\")\n",
    "    print(content)\n",
    "    print(f\"{'='*60}\\n\")\n",
    "\n",
    "def print_plan_step(step_num: int, action: str, details: str, status: str = \"pending\"):\n",
    "    \"\"\"Format plan step output\"\"\"\n",
    "    status_icons = {\n",
    "        \"pending\": \"⏳\",\n",
    "        \"running\": \"🔄\",\n",
    "        \"completed\": \"✅\",\n",
    "        \"failed\": \"❌\",\n",
    "        \"skipped\": \"⏭️\"\n",
    "    }\n",
    "    icon = status_icons.get(status, \"📋\")\n",
    "    print(f\"{icon} Step {step_num}: {action}\")\n",
    "    print(f\"    Details: {details}\")\n",
    "    if status != \"pending\":\n",
    "        print(f\"    Status: {status.title()}\")\n",
    "    print()\n",
    "\n",
    "print(\"✅ Planning system environment ready!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "planning-data-structures",
   "metadata": {},
   "source": [
    "## 📋 Core Planning Data Structures\n",
    "\n",
    "Let's define the fundamental data structures that will power our planning system."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "planning-structures",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Core planning data structures\n",
    "\n",
    "class TaskStatus(Enum):\n",
    "    \"\"\"Status of individual tasks in a plan\"\"\"\n",
    "    PENDING = \"pending\"\n",
    "    READY = \"ready\"           # Dependencies satisfied\n",
    "    RUNNING = \"running\"\n",
    "    COMPLETED = \"completed\"\n",
    "    FAILED = \"failed\"\n",
    "    SKIPPED = \"skipped\"\n",
    "    BLOCKED = \"blocked\"       # Dependencies not satisfied\n",
    "\n",
    "class PlanStatus(Enum):\n",
    "    \"\"\"Overall status of a plan\"\"\"\n",
    "    DRAFT = \"draft\"\n",
    "    ACTIVE = \"active\"\n",
    "    COMPLETED = \"completed\"\n",
    "    FAILED = \"failed\"\n",
    "    PAUSED = \"paused\"\n",
    "    CANCELLED = \"cancelled\"\n",
    "\n",
    "class Priority(Enum):\n",
    "    \"\"\"Task priority levels\"\"\"\n",
    "    LOW = 1\n",
    "    MEDIUM = 2\n",
    "    HIGH = 3\n",
    "    CRITICAL = 4\n",
    "    URGENT = 5\n",
    "\n",
    "@dataclass\n",
    "class Condition:\n",
    "    \"\"\"Represents a condition that must be met\"\"\"\n",
    "    name: str\n",
    "    description: str\n",
    "    check_function: callable = None\n",
    "    satisfied: bool = False\n",
    "    \n",
    "    def evaluate(self, context: Dict[str, Any]) -> bool:\n",
    "        \"\"\"Evaluate if condition is satisfied given current context\"\"\"\n",
    "        if self.check_function:\n",
    "            self.satisfied = self.check_function(context)\n",
    "        return self.satisfied\n",
    "\n",
    "@dataclass\n",
    "class Resource:\n",
    "    \"\"\"Represents a resource required for task execution\"\"\"\n",
    "    name: str\n",
    "    type: str  # \"tool\", \"data\", \"credential\", \"time\", etc.\n",
    "    required_amount: float = 1.0\n",
    "    available_amount: float = 1.0\n",
    "    renewable: bool = True\n",
    "    \n",
    "    @property\n",
    "    def is_available(self) -> bool:\n",
    "        return self.available_amount >= self.required_amount\n",
    "\n",
    "@dataclass\n",
    "class Task:\n",
    "    \"\"\"Represents a single task in a plan\"\"\"\n",
    "    id: str\n",
    "    name: str\n",
    "    description: str\n",
    "    action: str                              # Tool/method to execute\n",
    "    parameters: Dict[str, Any] = field(default_factory=dict)\n",
    "    \n",
    "    # Status and progress\n",
    "    status: TaskStatus = TaskStatus.PENDING\n",
    "    priority: Priority = Priority.MEDIUM\n",
    "    progress: float = 0.0                    # 0.0 to 1.0\n",
    "    \n",
    "    # Dependencies and relationships\n",
    "    dependencies: List[str] = field(default_factory=list)  # Task IDs that must complete first\n",
    "    dependents: List[str] = field(default_factory=list)    # Tasks that depend on this one\n",
    "    \n",
    "    # Conditions and resources\n",
    "    preconditions: List[Condition] = field(default_factory=list)\n",
    "    postconditions: List[Condition] = field(default_factory=list)\n",
    "    required_resources: List[Resource] = field(default_factory=list)\n",
    "    \n",
    "    # Timing and constraints\n",
    "    estimated_duration: Optional[timedelta] = None\n",
    "    actual_duration: Optional[timedelta] = None\n",
    "    deadline: Optional[datetime] = None\n",
    "    earliest_start: Optional[datetime] = None\n",
    "    \n",
    "    # Execution tracking\n",
    "    start_time: Optional[datetime] = None\n",
    "    end_time: Optional[datetime] = None\n",
    "    result: Any = None\n",
    "    error: Optional[str] = None\n",
    "    retry_count: int = 0\n",
    "    max_retries: int = 3\n",
    "    \n",
    "    def can_start(self, completed_tasks: Set[str], context: Dict[str, Any]) -> bool:\n",
    "        \"\"\"Check if task can be started given current state\"\"\"\n",
    "        # Check dependencies\n",
    "        if not all(dep_id in completed_tasks for dep_id in self.dependencies):\n",
    "            return False\n",
    "        \n",
    "        # Check preconditions\n",
    "        if not all(condition.evaluate(context) for condition in self.preconditions):\n",
    "            return False\n",
    "        \n",
    "        # Check resources\n",
    "        if not all(resource.is_available for resource in self.required_resources):\n",
    "            return False\n",
    "        \n",
    "        # Check timing constraints\n",
    "        now = datetime.now()\n",
    "        if self.earliest_start and now < self.earliest_start:\n",
    "            return False\n",
    "        \n",
    "        return True\n",
    "    \n",
    "    def is_overdue(self) -> bool:\n",
    "        \"\"\"Check if task is past its deadline\"\"\"\n",
    "        return self.deadline and datetime.now() > self.deadline\n",
    "\n",
    "@dataclass\n",
    "class Plan:\n",
    "    \"\"\"Represents a complete plan with multiple tasks\"\"\"\n",
    "    id: str\n",
    "    name: str\n",
    "    description: str\n",
    "    goal: str\n",
    "    \n",
    "    # Plan structure\n",
    "    tasks: Dict[str, Task] = field(default_factory=dict)\n",
    "    task_order: List[str] = field(default_factory=list)  # Topological order\n",
    "    \n",
    "    # Status and tracking\n",
    "    status: PlanStatus = PlanStatus.DRAFT\n",
    "    created_at: datetime = field(default_factory=datetime.now)\n",
    "    started_at: Optional[datetime] = None\n",
    "    completed_at: Optional[datetime] = None\n",
    "    \n",
    "    # Execution context\n",
    "    context: Dict[str, Any] = field(default_factory=dict)\n",
    "    resources: Dict[str, Resource] = field(default_factory=dict)\n",
    "    \n",
    "    # Statistics\n",
    "    total_estimated_duration: Optional[timedelta] = None\n",
    "    actual_duration: Optional[timedelta] = None\n",
    "    \n",
    "    def add_task(self, task: Task) -> bool:\n",
    "        \"\"\"Add a task to the plan\"\"\"\n",
    "        if task.id in self.tasks:\n",
    "            logger.warning(f\"Task {task.id} already exists in plan\")\n",
    "            return False\n",
    "        \n",
    "        self.tasks[task.id] = task\n",
    "        self._update_task_order()\n",
    "        return True\n",
    "    \n",
    "    def remove_task(self, task_id: str) -> bool:\n",
    "        \"\"\"Remove a task from the plan\"\"\"\n",
    "        if task_id not in self.tasks:\n",
    "            return False\n",
    "        \n",
    "        # Remove dependencies\n",
    "        task = self.tasks[task_id]\n",
    "        for dep_id in task.dependencies:\n",
    "            if dep_id in self.tasks:\n",
    "                self.tasks[dep_id].dependents.remove(task_id)\n",
    "        \n",
    "        for dependent_id in task.dependents:\n",
    "            if dependent_id in self.tasks:\n",
    "                self.tasks[dependent_id].dependencies.remove(task_id)\n",
    "        \n",
    "        del self.tasks[task_id]\n",
    "        self._update_task_order()\n",
    "        return True\n",
    "    \n",
    "    def get_ready_tasks(self) -> List[Task]:\n",
    "        \"\"\"Get tasks that are ready to execute\"\"\"\n",
    "        completed_tasks = {tid for tid, task in self.tasks.items() \n",
    "                          if task.status == TaskStatus.COMPLETED}\n",
    "        \n",
    "        ready_tasks = []\n",
    "        for task in self.tasks.values():\n",
    "            if (task.status == TaskStatus.PENDING and \n",
    "                task.can_start(completed_tasks, self.context)):\n",
    "                ready_tasks.append(task)\n",
    "        \n",
    "        # Sort by priority and then by position in task order\n",
    "        ready_tasks.sort(key=lambda t: (t.priority.value, self.task_order.index(t.id)), reverse=True)\n",
    "        return ready_tasks\n",
    "    \n",
    "    def get_progress(self) -> float:\n",
    "        \"\"\"Calculate overall plan progress (0.0 to 1.0)\"\"\"\n",
    "        if not self.tasks:\n",
    "            return 1.0\n",
    "        \n",
    "        total_progress = sum(task.progress for task in self.tasks.values())\n",
    "        return total_progress / len(self.tasks)\n",
    "    \n",
    "    def is_complete(self) -> bool:\n",
    "        \"\"\"Check if all tasks are completed\"\"\"\n",
    "        return all(task.status == TaskStatus.COMPLETED for task in self.tasks.values())\n",
    "    \n",
    "    def has_failed(self) -> bool:\n",
    "        \"\"\"Check if any critical task has failed\"\"\"\n",
    "        return any(task.status == TaskStatus.FAILED and task.priority.value >= Priority.HIGH.value \n",
    "                  for task in self.tasks.values())\n",
    "    \n",
    "    def _update_task_order(self):\n",
    "        \"\"\"Update topological ordering of tasks\"\"\"\n",
    "        # Build dependency graph\n",
    "        graph = defaultdict(list)\n",
    "        in_degree = defaultdict(int)\n",
    "        \n",
    "        for task_id in self.tasks:\n",
    "            in_degree[task_id] = 0\n",
    "        \n",
    "        for task_id, task in self.tasks.items():\n",
    "            for dep_id in task.dependencies:\n",
    "                graph[dep_id].append(task_id)\n",
    "                in_degree[task_id] += 1\n",
    "        \n",
    "        # Topological sort\n",
    "        queue = deque([task_id for task_id in self.tasks if in_degree[task_id] == 0])\n",
    "        self.task_order = []\n",
    "        \n",
    "        while queue:\n",
    "            current = queue.popleft()\n",
    "            self.task_order.append(current)\n",
    "            \n",
    "            for neighbor in graph[current]:\n",
    "                in_degree[neighbor] -= 1\n",
    "                if in_degree[neighbor] == 0:\n",
    "                    queue.append(neighbor)\n",
    "        \n",
    "        # Check for circular dependencies\n",
    "        if len(self.task_order) != len(self.tasks):\n",
    "            logger.error(\"Circular dependency detected in plan\")\n",
    "            self.task_order = list(self.tasks.keys())  # Fallback\n",
    "\n",
    "print(\"✅ Planning data structures defined!\")\n",
    "print(\"📋 Core components: Task, Plan, Condition, Resource\")\n",
    "print(\"🔄 Status tracking: TaskStatus, PlanStatus, Priority\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "hierarchical-planner",
   "metadata": {},
   "source": [
    "## 🌲 Hierarchical Task Network (HTN) Planner\n",
    "\n",
    "HTN planning works by decomposing high-level tasks into lower-level subtasks until we reach primitive actions. This mimics how humans naturally break down complex problems."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "htn-planner",
   "metadata": {},
   "outputs": [],
   "source": [
    "class HTNPlanner:\n",
    "    \"\"\"Hierarchical Task Network planner for goal decomposition\"\"\"\n",
    "    \n",
    "    def __init__(self, llm_client=None):\n",
    "        self.llm_client = llm_client\n",
    "        self.decomposition_rules = {}  # Task type -> decomposition function\n",
    "        self.primitive_actions = set()  # Actions that don't need further decomposition\n",
    "        self.planning_history = []     # Keep track of planning decisions\n",
    "    \n",
    "    def register_decomposition_rule(self, task_type: str, decomposition_func: callable):\n",
    "        \"\"\"Register a rule for decomposing a specific type of task\"\"\"\n",
    "        self.decomposition_rules[task_type] = decomposition_func\n",
    "        logger.info(f\"Registered decomposition rule for task type: {task_type}\")\n",
    "    \n",
    "    def register_primitive_action(self, action_name: str):\n",
    "        \"\"\"Register an action as primitive (no further decomposition needed)\"\"\"\n",
    "        self.primitive_actions.add(action_name)\n",
    "        logger.info(f\"Registered primitive action: {action_name}\")\n",
    "    \n",
    "    def create_plan(self, goal: str, context: Dict[str, Any] = None) -> Plan:\n",
    "        \"\"\"Create a hierarchical plan for achieving the given goal\"\"\"\n",
    "        context = context or {}\n",
    "        \n",
    "        plan = Plan(\n",
    "            id=str(uuid.uuid4()),\n",
    "            name=f\"Plan for: {goal}\",\n",
    "            description=f\"Hierarchical plan to achieve: {goal}\",\n",
    "            goal=goal,\n",
    "            context=context\n",
    "        )\n",
    "        \n",
    "        logger.info(f\"Creating HTN plan for goal: {goal}\")\n",
    "        \n",
    "        # Start with the root task\n",
    "        root_task = Task(\n",
    "            id=\"root\",\n",
    "            name=goal,\n",
    "            description=f\"Root task: {goal}\",\n",
    "            action=\"decompose\",\n",
    "            priority=Priority.HIGH\n",
    "        )\n",
    "        \n",
    "        # Decompose the goal hierarchically\n",
    "        decomposed_tasks = self._decompose_task(root_task, context, plan)\n",
    "        \n",
    "        # Add all tasks to the plan\n",
    "        for task in decomposed_tasks:\n",
    "            plan.add_task(task)\n",
    "        \n",
    "        # Estimate total duration\n",
    "        plan.total_estimated_duration = self._estimate_plan_duration(plan)\n",
    "        \n",
    "        logger.info(f\"HTN plan created with {len(plan.tasks)} tasks\")\n",
    "        return plan\n",
    "    \n",
    "    def _decompose_task(self, task: Task, context: Dict[str, Any], plan: Plan) -> List[Task]:\n",
    "        \"\"\"Recursively decompose a task into subtasks\"\"\"\n",
    "        \n",
    "        # If task is primitive, return it as-is\n",
    "        if task.action in self.primitive_actions:\n",
    "            return [task]\n",
    "        \n",
    "        # Try to find a decomposition rule\n",
    "        task_type = self._classify_task(task)\n",
    "        \n",
    "        if task_type in self.decomposition_rules:\n",
    "            # Use predefined decomposition rule\n",
    "            subtasks = self.decomposition_rules[task_type](task, context)\n",
    "        else:\n",
    "            # Use LLM-based decomposition\n",
    "            subtasks = self._llm_decompose_task(task, context)\n",
    "        \n",
    "        # Recursively decompose subtasks\n",
    "        all_tasks = []\n",
    "        for subtask in subtasks:\n",
    "            decomposed_subtasks = self._decompose_task(subtask, context, plan)\n",
    "            all_tasks.extend(decomposed_subtasks)\n",
    "        \n",
    "        # Record planning decision\n",
    "        self.planning_history.append({\n",
    "            'timestamp': datetime.now(),\n",
    "            'action': 'decompose',\n",
    "            'parent_task': task.name,\n",
    "            'subtasks': [t.name for t in subtasks],\n",
    "            'method': task_type if task_type in self.decomposition_rules else 'llm'\n",
    "        })\n",
    "        \n",
    "        return all_tasks\n",
    "    \n",
    "    def _classify_task(self, task: Task) -> str:\n",
    "        \"\"\"Classify task type for decomposition\"\"\"\n",
    "        task_name = task.name.lower()\n",
    "        task_desc = task.description.lower()\n",
    "        \n",
    "        # Simple keyword-based classification\n",
    "        if any(word in task_name for word in ['analyze', 'analysis', 'study']):\n",
    "            return 'analysis'\n",
    "        elif any(word in task_name for word in ['report', 'document', 'write']):\n",
    "            return 'documentation'\n",
    "        elif any(word in task_name for word in ['research', 'investigate', 'find']):\n",
    "            return 'research'\n",
    "        elif any(word in task_name for word in ['communicate', 'notify', 'send']):\n",
    "            return 'communication'\n",
    "        elif any(word in task_name for word in ['process', 'transform', 'convert']):\n",
    "            return 'data_processing'\n",
    "        else:\n",
    "            return 'general'\n",
    "    \n",
    "    def _llm_decompose_task(self, task: Task, context: Dict[str, Any]) -> List[Task]:\n",
    "        \"\"\"Use LLM to decompose a task into subtasks\"\"\"\n",
    "        \n",
    "        if not self.llm_client:\n",
    "            # Fallback to simple decomposition\n",
    "            return self._simple_decompose_task(task)\n",
    "        \n",
    "        decomposition_prompt = f\"\"\"\n",
    "Decompose the following task into specific, actionable subtasks:\n",
    "\n",
    "Task: {task.name}\n",
    "Description: {task.description}\n",
    "Context: {json.dumps(context, indent=2)}\n",
    "\n",
    "Available tools/actions: database_query, web_api, file_processor, email_sender\n",
    "\n",
    "Requirements:\n",
    "1. Break the task into 2-5 concrete subtasks\n",
    "2. Each subtask should be specific and actionable\n",
    "3. Consider dependencies between subtasks\n",
    "4. Estimate duration for each subtask (in minutes)\n",
    "5. Assign appropriate priority (1-5, where 5 is highest)\n",
    "\n",
    "Respond with JSON format:\n",
    "{{\n",
    "  \"subtasks\": [\n",
    "    {{\n",
    "      \"name\": \"Subtask name\",\n",
    "      \"description\": \"Detailed description\",\n",
    "      \"action\": \"tool_name or action_type\",\n",
    "      \"parameters\": {{\"key\": \"value\"}},\n",
    "      \"estimated_duration_minutes\": 30,\n",
    "      \"priority\": 3,\n",
    "      \"dependencies\": [\"other_subtask_names\"]\n",
    "    }}\n",
    "  ]\n",
    "}}\n",
    "\"\"\"\n",
    "        \n",
    "        try:\n",
    "            response = self.llm_client.chat.completions.create(\n",
    "                model=\"gpt-4\",\n",
    "                messages=[{\"role\": \"user\", \"content\": decomposition_prompt}],\n",
    "                temperature=0.2,\n",
    "                max_tokens=1500\n",
    "            )\n",
    "            \n",
    "            response_text = response.choices[0].message.content\n",
    "            \n",
    "            # Extract JSON from response\n",
    "            json_start = response_text.find('{')\n",
    "            json_end = response_text.rfind('}') + 1\n",
    "            if json_start >= 0 and json_end > json_start:\n",
    "                json_text = response_text[json_start:json_end]\n",
    "                decomposition_data = json.loads(json_text)\n",
    "                \n",
    "                subtasks = []\n",
    "                for i, subtask_data in enumerate(decomposition_data['subtasks']):\n",
    "                    subtask = Task(\n",
    "                        id=f\"{task.id}_sub_{i}\",\n",
    "                        name=subtask_data['name'],\n",
    "                        description=subtask_data['description'],\n",
    "                        action=subtask_data['action'],\n",
    "                        parameters=subtask_data.get('parameters', {}),\n",
    "                        estimated_duration=timedelta(minutes=subtask_data.get('estimated_duration_minutes', 30)),\n",
    "                        priority=Priority(subtask_data.get('priority', 3))\n",
    "                    )\n",
    "                    subtasks.append(subtask)\n",
    "                \n",
    "                # Set up dependencies\n",
    "                for i, subtask_data in enumerate(decomposition_data['subtasks']):\n",
    "                    deps = subtask_data.get('dependencies', [])\n",
    "                    for dep_name in deps:\n",
    "                        # Find dependency by name\n",
    "                        for j, dep_task in enumerate(subtasks):\n",
    "                            if dep_task.name == dep_name:\n",
    "                                subtasks[i].dependencies.append(dep_task.id)\n",
    "                                dep_task.dependents.append(subtasks[i].id)\n",
    "                                break\n",
    "                \n",
    "                return subtasks\n",
    "        \n",
    "        except Exception as e:\n",
    "            logger.error(f\"LLM decomposition failed: {e}\")\n",
    "        \n",
    "        # Fallback to simple decomposition\n",
    "        return self._simple_decompose_task(task)\n",
    "    \n",
    "    def _simple_decompose_task(self, task: Task) -> List[Task]:\n",
    "        \"\"\"Simple fallback decomposition based on task classification\"\"\"\n",
    "        task_type = self._classify_task(task)\n",
    "        \n",
    "        if task_type == 'analysis':\n",
    "            return [\n",
    "                Task(\n",
    "                    id=f\"{task.id}_gather\",\n",
    "                    name=f\"Gather data for {task.name}\",\n",
    "                    description=f\"Collect relevant data for analysis\",\n",
    "                    action=\"database_query\",\n",
    "                    estimated_duration=timedelta(minutes=15)\n",
    "                ),\n",
    "                Task(\n",
    "                    id=f\"{task.id}_analyze\",\n",
    "                    name=f\"Perform {task.name}\",\n",
    "                    description=f\"Analyze the gathered data\",\n",
    "                    action=\"analyze_data\",\n",
    "                    dependencies=[f\"{task.id}_gather\"],\n",
    "                    estimated_duration=timedelta(minutes=30)\n",
    "                )\n",
    "            ]\n",
    "        elif task_type == 'documentation':\n",
    "            return [\n",
    "                Task(\n",
    "                    id=f\"{task.id}_draft\",\n",
    "                    name=f\"Draft {task.name}\",\n",
    "                    description=f\"Create initial draft\",\n",
    "                    action=\"file_processor\",\n",
    "                    estimated_duration=timedelta(minutes=45)\n",
    "                ),\n",
    "                Task(\n",
    "                    id=f\"{task.id}_review\",\n",
    "                    name=f\"Review {task.name}\",\n",
    "                    description=f\"Review and finalize document\",\n",
    "                    action=\"review_document\",\n",
    "                    dependencies=[f\"{task.id}_draft\"],\n",
    "                    estimated_duration=timedelta(minutes=15)\n",
    "                )\n",
    "            ]\n",
    "        else:\n",
    "            # Generic decomposition\n",
    "            return [\n",
    "                Task(\n",
    "                    id=f\"{task.id}_execute\",\n",
    "                    name=f\"Execute {task.name}\",\n",
    "                    description=task.description,\n",
    "                    action=task.action,\n",
    "                    parameters=task.parameters,\n",
    "                    estimated_duration=timedelta(minutes=30)\n",
    "                )\n",
    "            ]\n",
    "    \n",
    "    def _estimate_plan_duration(self, plan: Plan) -> timedelta:\n",
    "        \"\"\"Estimate total plan duration considering dependencies\"\"\"\n",
    "        if not plan.tasks:\n",
    "            return timedelta(0)\n",
    "        \n",
    "        # Simple critical path estimation\n",
    "        max_duration = timedelta(0)\n",
    "        for task in plan.tasks.values():\n",
    "            if task.estimated_duration:\n",
    "                max_duration = max(max_duration, task.estimated_duration)\n",
    "        \n",
    "        # Add some buffer for coordination overhead\n",
    "        return max_duration * len(plan.tasks) * 0.3  # Rough estimate\n",
    "\n",
    "# Register some common decomposition rules\n",
    "htn_planner = HTNPlanner(llm_client=openai.OpenAI(api_key=os.getenv(\"OPENAI_API_KEY\", \"your-api-key\")))\n",
    "\n",
    "# Register primitive actions\n",
    "primitive_actions = [\n",
    "    'database_query', 'web_api', 'file_processor', 'email_sender',\n",
    "    'calculate', 'validate', 'format', 'send', 'save', 'load'\n",
    "]\n",
    "\n",
    "for action in primitive_actions:\n",
    "    htn_planner.register_primitive_action(action)\n",
    "\n",
    "print(\"✅ HTN Planner created!\")\n",
    "print(f\"🔧 Registered {len(primitive_actions)} primitive actions\")\n",
    "print(\"🌲 Ready for hierarchical task decomposition\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "guided-exercise-planning",
   "metadata": {},
   "source": [
    "## 💡 Guided Exercise: Build a Goal-Oriented Action Planner\n",
    "\n",
    "Now it's your turn! Implement a Goal-Oriented Action Planning (GOAP) system that works backwards from goals to find action sequences.\n",
    "\n",
    "**GOAP Concept:** Start with the goal state and work backwards to find a sequence of actions that can achieve it from the current state."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "guided-exercise-goap",
   "metadata": {},
   "outputs": [],
   "source": [
    "class GOAPPlanner:\n",
    "    \"\"\"Goal-Oriented Action Planning system\"\"\"\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.actions = {}  # action_name -> Action definition\n",
    "        self.world_state = {}  # Current state of the world\n",
    "    \n",
    "    def register_action(self, name: str, preconditions: Dict[str, Any], \n",
    "                       effects: Dict[str, Any], cost: float = 1.0):\n",
    "        \"\"\"Register an action with its preconditions and effects\"\"\"\n",
    "        self.actions[name] = {\n",
    "            'preconditions': preconditions,\n",
    "            'effects': effects,\n",
    "            'cost': cost\n",
    "        }\n",
    "    \n",
    "    def set_world_state(self, state: Dict[str, Any]):\n",
    "        \"\"\"Set the current world state\"\"\"\n",
    "        self.world_state = state.copy()\n",
    "    \n",
    "    def plan(self, goal_state: Dict[str, Any]) -> List[str]:\n",
    "        \"\"\"\n",
    "        Find a sequence of actions to achieve the goal state.\n",
    "        \n",
    "        YOUR TASK: Implement the GOAP planning algorithm using A* search.\n",
    "        \n",
    "        Steps to implement:\n",
    "        1. Start from the goal state and work backwards\n",
    "        2. Use A* search to find the optimal action sequence\n",
    "        3. Each node represents a world state\n",
    "        4. Each edge represents an action\n",
    "        5. Return the sequence of actions from start to goal\n",
    "        \"\"\"\n",
    "        \n",
    "        ### START CODE HERE ###\n",
    "        \n",
    "        # Check if goal is already satisfied\n",
    "        if self._state_satisfies_goal(self.world_state, goal_state):\n",
    "            return []  # No actions needed\n",
    "        \n",
    "        # A* search data structures\n",
    "        # Priority queue: (f_cost, g_cost, state, action_sequence)\n",
    "        open_set = []\n",
    "        closed_set = set()\n",
    "        \n",
    "        # Add starting state\n",
    "        start_state_key = self._state_to_key(self.world_state)\n",
    "        heapq.heappush(open_set, (\n",
    "            self._heuristic(self.world_state, goal_state),  # f_cost = h_cost (g_cost = 0)\n",
    "            0,                                              # g_cost\n",
    "            self.world_state.copy(),                       # current state\n",
    "            []                                             # action sequence\n",
    "        ))\n",
    "        \n",
    "        while open_set:\n",
    "            # Get the node with lowest f_cost\n",
    "            f_cost, g_cost, current_state, action_sequence = heapq.heappop(open_set)\n",
    "            \n",
    "            # Convert state to hashable key for closed set\n",
    "            state_key = self._state_to_key(current_state)\n",
    "            \n",
    "            # Skip if already processed\n",
    "            if state_key in closed_set:\n",
    "                continue\n",
    "            \n",
    "            # Add to closed set\n",
    "            closed_set.add(state_key)\n",
    "            \n",
    "            # Check if we've reached the goal\n",
    "            if self._state_satisfies_goal(current_state, goal_state):\n",
    "                return action_sequence\n",
    "            \n",
    "            # Explore all possible actions from current state\n",
    "            for action_name, action_data in self.actions.items():\n",
    "                # YOUR CODE: Check if action can be applied to current state\n",
    "                if self._can_apply_action(current_state, action_data['preconditions']):\n",
    "                    # YOUR CODE: Apply action to get new state\n",
    "                    new_state = self._apply_action(current_state, action_data['effects'])\n",
    "                    new_state_key = self._state_to_key(new_state)\n",
    "                    \n",
    "                    # Skip if already processed\n",
    "                    if new_state_key in closed_set:\n",
    "                        continue\n",
    "                    \n",
    "                    # Calculate costs\n",
    "                    new_g_cost = g_cost + action_data['cost']\n",
    "                    h_cost = self._heuristic(new_state, goal_state)\n",
    "                    new_f_cost = new_g_cost + h_cost\n",
    "                    \n",
    "                    # Add to open set\n",
    "                    new_action_sequence = action_sequence + [action_name]\n",
    "                    heapq.heappush(open_set, (\n",
    "                        new_f_cost,\n",
    "                        new_g_cost,\n",
    "                        new_state,\n",
    "                        new_action_sequence\n",
    "                    ))\n",
    "        \n",
    "        # No solution found\n",
    "        return None\n",
    "        \n",
    "        ### END CODE HERE ###\n",
    "    \n",
    "    def _state_satisfies_goal(self, state: Dict[str, Any], goal: Dict[str, Any]) -> bool:\n",
    "        \"\"\"Check if current state satisfies the goal\"\"\"\n",
    "        for key, value in goal.items():\n",
    "            if state.get(key) != value:\n",
    "                return False\n",
    "        return True\n",
    "    \n",
    "    def _can_apply_action(self, state: Dict[str, Any], preconditions: Dict[str, Any]) -> bool:\n",
    "        \"\"\"Check if action preconditions are satisfied in current state\"\"\"\n",
    "        for key, value in preconditions.items():\n",
    "            if state.get(key) != value:\n",
    "                return False\n",
    "        return True\n",
    "    \n",
    "    def _apply_action(self, state: Dict[str, Any], effects: Dict[str, Any]) -> Dict[str, Any]:\n",
    "        \"\"\"Apply action effects to state and return new state\"\"\"\n",
    "        new_state = state.copy()\n",
    "        new_state.update(effects)\n",
    "        return new_state\n",
    "    \n",
    "    def _state_to_key(self, state: Dict[str, Any]) -> str:\n",
    "        \"\"\"Convert state dict to hashable string key\"\"\"\n",
    "        return json.dumps(state, sort_keys=True)\n",
    "    \n",
    "    def _heuristic(self, state: Dict[str, Any], goal: Dict[str, Any]) -> float:\n",
    "        \"\"\"\n",
    "        Heuristic function for A* search.\n",
    "        \n",
    "        YOUR TASK: Implement a heuristic that estimates the cost to reach the goal.\n",
    "        \n",
    "        A good heuristic should be:\n",
    "        - Admissible (never overestimate the actual cost)\n",
    "        - Consistent (satisfies triangle inequality)\n",
    "        \"\"\"\n",
    "        \n",
    "        ### START CODE HERE ###\n",
    "        \n",
    "        # Simple heuristic: count unsatisfied goal conditions\n",
    "        unsatisfied_count = 0\n",
    "        for key, value in goal.items():\n",
    "            if state.get(key) != value:\n",
    "                unsatisfied_count += 1\n",
    "        \n",
    "        # Return the count as heuristic cost\n",
    "        return float(unsatisfied_count)\n",
    "        \n",
    "        ### END CODE HERE ###\n",
    "\n",
    "# Test the GOAP planner\n",
    "goap_planner = GOAPPlanner()\n",
    "\n",
    "# Define some actions for a simple domain\n",
    "goap_planner.register_action(\n",
    "    name=\"gather_data\",\n",
    "    preconditions={\"has_database_access\": True},\n",
    "    effects={\"has_data\": True},\n",
    "    cost=2.0\n",
    ")\n",
    "\n",
    "goap_planner.register_action(\n",
    "    name=\"connect_to_database\",\n",
    "    preconditions={\"has_credentials\": True},\n",
    "    effects={\"has_database_access\": True},\n",
    "    cost=1.0\n",
    ")\n",
    "\n",
    "goap_planner.register_action(\n",
    "    name=\"analyze_data\",\n",
    "    preconditions={\"has_data\": True, \"has_analysis_tool\": True},\n",
    "    effects={\"has_analysis\": True},\n",
    "    cost=3.0\n",
    ")\n",
    "\n",
    "goap_planner.register_action(\n",
    "    name=\"generate_report\",\n",
    "    preconditions={\"has_analysis\": True},\n",
    "    effects={\"has_report\": True},\n",
    "    cost=2.0\n",
    ")\n",
    "\n",
    "# Set initial world state\n",
    "initial_state = {\n",
    "    \"has_credentials\": True,\n",
    "    \"has_analysis_tool\": True,\n",
    "    \"has_database_access\": False,\n",
    "    \"has_data\": False,\n",
    "    \"has_analysis\": False,\n",
    "    \"has_report\": False\n",
    "}\n",
    "\n",
    "goap_planner.set_world_state(initial_state)\n",
    "\n",
    "# Define goal\n",
    "goal = {\"has_report\": True}\n",
    "\n",
    "print(\"🎯 Testing GOAP Planner:\")\n",
    "print(f\"Initial state: {initial_state}\")\n",
    "print(f\"Goal: {goal}\")\n",
    "\n",
    "# Find plan\n",
    "action_sequence = goap_planner.plan(goal)\n",
    "\n",
    "if action_sequence:\n",
    "    print(f\"\\n✅ Found plan with {len(action_sequence)} actions:\")\n",
    "    for i, action in enumerate(action_sequence, 1):\n",
    "        print(f\"  {i}. {action}\")\n",
    "else:\n",
    "    print(\"\\n❌ No plan found to achieve the goal\")\n",
    "\n",
    "print(f\"\\n📊 GOAP planner configured with {len(goap_planner.actions)} actions\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "solution-reveal-goap",
   "metadata": {},
   "source": [
    "### 🔍 Solution Reveal - GOAP Planner\n",
    "\n",
    "Here's the complete solution for the GOAP planner:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "solution-goap",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION - GOAP Planning Algorithm\n",
    "\"\"\"\n",
    "The key insight in GOAP is using A* search where:\n",
    "- Each node represents a world state\n",
    "- Each edge represents an action that transforms the state\n",
    "- We search from current state to goal state\n",
    "- The heuristic estimates remaining cost to reach goal\n",
    "\n",
    "Here's the corrected implementation:\n",
    "\n",
    "def _can_apply_action(self, state, preconditions):\n",
    "    for key, value in preconditions.items():\n",
    "        if state.get(key) != value:\n",
    "            return False\n",
    "    return True\n",
    "\n",
    "def _apply_action(self, state, effects):\n",
    "    new_state = state.copy()\n",
    "    new_state.update(effects)\n",
    "    return new_state\n",
    "\n",
    "def _heuristic(self, state, goal):\n",
    "    # Count unsatisfied goal conditions\n",
    "    unsatisfied = 0\n",
    "    for key, value in goal.items():\n",
    "        if state.get(key) != value:\n",
    "            unsatisfied += 1\n",
    "    return float(unsatisfied)\n",
    "\n",
    "The A* search ensures we find the optimal (lowest cost) plan.\n",
    "\"\"\"\n",
    "\n",
    "print(\"💡 GOAP Solution explained:\")\n",
    "print(\"  • A* search finds optimal action sequences\")\n",
    "print(\"  • Preconditions must be satisfied to apply actions\")\n",
    "print(\"  • Effects modify the world state\")\n",
    "print(\"  • Heuristic guides search toward goal\")\n",
    "print(\"  • Works backwards from goal to current state\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "plan-executor",
   "metadata": {},
   "source": [
    "## ⚙️ Adaptive Plan Executor\n",
    "\n",
    "Now let's build an executor that can run plans while adapting to changing conditions and handling failures."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plan-executor-impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "class AdaptivePlanExecutor:\n",
    "    \"\"\"Executes plans with monitoring, adaptation, and error recovery\"\"\"\n",
    "    \n",
    "    def __init__(self, tool_manager=None, memory_manager=None, replanner=None):\n",
    "        self.tool_manager = tool_manager\n",
    "        self.memory_manager = memory_manager\n",
    "        self.replanner = replanner or htn_planner\n",
    "        \n",
    "        # Execution state\n",
    "        self.current_plan = None\n",
    "        self.execution_context = {}\n",
    "        self.monitoring_data = []\n",
    "        \n",
    "        # Configuration\n",
    "        self.max_execution_time = timedelta(hours=2)\n",
    "        self.monitoring_interval = 5  # seconds\n",
    "        self.replan_threshold = 0.3   # Replan if progress drops below 30%\n",
    "    \n",
    "    async def execute_plan(self, plan: Plan) -> Dict[str, Any]:\n",
    "        \"\"\"Execute a plan with adaptive monitoring and error recovery\"\"\"\n",
    "        \n",
    "        self.current_plan = plan\n",
    "        plan.status = PlanStatus.ACTIVE\n",
    "        plan.started_at = datetime.now()\n",
    "        \n",
    "        logger.info(f\"Starting execution of plan: {plan.name}\")\n",
    "        print_section(\"PLAN EXECUTION STARTED\", f\"Executing: {plan.name}\\nGoal: {plan.goal}\")\n",
    "        \n",
    "        execution_result = {\n",
    "            'plan_id': plan.id,\n",
    "            'started_at': plan.started_at,\n",
    "            'status': 'running',\n",
    "            'tasks_completed': 0,\n",
    "            'tasks_failed': 0,\n",
    "            'replanning_events': 0,\n",
    "            'error_recoveries': 0\n",
    "        }\n",
    "        \n",
    "        try:\n",
    "            # Main execution loop\n",
    "            while not plan.is_complete() and not plan.has_failed():\n",
    "                # Check for timeout\n",
    "                if datetime.now() - plan.started_at > self.max_execution_time:\n",
    "                    logger.error(\"Plan execution timed out\")\n",
    "                    plan.status = PlanStatus.FAILED\n",
    "                    execution_result['status'] = 'timeout'\n",
    "                    break\n",
    "                \n",
    "                # Get ready tasks\n",
    "                ready_tasks = plan.get_ready_tasks()\n",
    "                \n",
    "                if not ready_tasks:\n",
    "                    # No tasks ready - check if we're blocked\n",
    "                    if self._is_plan_blocked(plan):\n",
    "                        logger.warning(\"Plan is blocked - attempting to replan\")\n",
    "                        replan_success = await self._attempt_replan(plan)\n",
    "                        execution_result['replanning_events'] += 1\n",
    "                        \n",
    "                        if not replan_success:\n",
    "                            logger.error(\"Replanning failed - plan execution blocked\")\n",
    "                            plan.status = PlanStatus.FAILED\n",
    "                            execution_result['status'] = 'blocked'\n",
    "                            break\n",
    "                        continue\n",
    "                    else:\n",
    "                        # Wait for running tasks to complete\n",
    "                        await asyncio.sleep(1)\n",
    "                        continue\n",
    "                \n",
    "                # Execute ready tasks (can run multiple in parallel)\n",
    "                execution_tasks = []\n",
    "                for task in ready_tasks[:3]:  # Limit parallelism\n",
    "                    task.status = TaskStatus.RUNNING\n",
    "                    execution_tasks.append(self._execute_task(task))\n",
    "                \n",
    "                # Wait for tasks to complete\n",
    "                task_results = await asyncio.gather(*execution_tasks, return_exceptions=True)\n",
    "                \n",
    "                # Process results\n",
    "                for i, result in enumerate(task_results):\n",
    "                    task = ready_tasks[i]\n",
    "                    \n",
    "                    if isinstance(result, Exception):\n",
    "                        logger.error(f\"Task {task.name} failed with exception: {result}\")\n",
    "                        await self._handle_task_failure(task, str(result), execution_result)\n",
    "                    elif result['success']:\n",
    "                        await self._handle_task_success(task, result, execution_result)\n",
    "                    else:\n",
    "                        await self._handle_task_failure(task, result.get('error', 'Unknown error'), execution_result)\n",
    "                \n",
    "                # Monitor and log progress\n",
    "                await self._monitor_progress(plan, execution_result)\n",
    "            \n",
    "            # Plan completed\n",
    "            if plan.is_complete():\n",
    "                plan.status = PlanStatus.COMPLETED\n",
    "                plan.completed_at = datetime.now()\n",
    "                execution_result['status'] = 'completed'\n",
    "                logger.info(f\"Plan {plan.name} completed successfully\")\n",
    "            elif plan.has_failed():\n",
    "                plan.status = PlanStatus.FAILED\n",
    "                execution_result['status'] = 'failed'\n",
    "                logger.error(f\"Plan {plan.name} failed\")\n",
    "        \n",
    "        except Exception as e:\n",
    "            logger.error(f\"Unexpected error during plan execution: {e}\")\n",
    "            plan.status = PlanStatus.FAILED\n",
    "            execution_result['status'] = 'error'\n",
    "            execution_result['error'] = str(e)\n",
    "        \n",
    "        finally:\n",
    "            execution_result['completed_at'] = datetime.now()\n",
    "            execution_result['total_duration'] = (\n",
    "                execution_result['completed_at'] - plan.started_at\n",
    "            ).total_seconds()\n",
    "            \n",
    "            # Final progress report\n",
    "            self._print_execution_summary(plan, execution_result)\n",
    "        \n",
    "        return execution_result\n",
    "    \n",
    "    async def _execute_task(self, task: Task) -> Dict[str, Any]:\n",
    "        \"\"\"Execute a single task\"\"\"\n",
    "        task.start_time = datetime.now()\n",
    "        \n",
    "        logger.info(f\"Executing task: {task.name}\")\n",
    "        print_plan_step(len([t for t in self.current_plan.tasks.values() if t.status == TaskStatus.COMPLETED]) + 1,\n",
    "                       task.name, task.description, \"running\")\n",
    "        \n",
    "        try:\n",
    "            if self.tool_manager and task.action in self.tool_manager.tools:\n",
    "                # Execute using tool manager\n",
    "                tool_result = self.tool_manager.execute_tool(task.action, task.parameters)\n",
    "                \n",
    "                if tool_result.is_success:\n",
    "                    task.result = tool_result.data\n",
    "                    return {\n",
    "                        'success': True,\n",
    "                        'result': tool_result.data,\n",
    "                        'execution_time': tool_result.execution_time\n",
    "                    }\n",
    "                else:\n",
    "                    return {\n",
    "                        'success': False,\n",
    "                        'error': tool_result.error\n",
    "                    }\n",
    "            else:\n",
    "                # Simulate task execution\n",
    "                await asyncio.sleep(random.uniform(0.5, 2.0))  # Simulate work\n",
    "                \n",
    "                # Random success/failure for demonstration\n",
    "                success = random.random() > 0.1  # 90% success rate\n",
    "                \n",
    "                if success:\n",
    "                    task.result = f\"Completed: {task.name}\"\n",
    "                    return {\n",
    "                        'success': True,\n",
    "                        'result': task.result\n",
    "                    }\n",
    "                else:\n",
    "                    return {\n",
    "                        'success': False,\n",
    "                        'error': 'Simulated task failure'\n",
    "                    }\n",
    "        \n",
    "        except Exception as e:\n",
    "            return {\n",
    "                'success': False,\n",
    "                'error': str(e)\n",
    "            }\n",
    "        \n",
    "        finally:\n",
    "            task.end_time = datetime.now()\n",
    "            if task.start_time:\n",
    "                task.actual_duration = task.end_time - task.start_time\n",
    "    \n",
    "    async def _handle_task_success(self, task: Task, result: Dict, execution_result: Dict):\n",
    "        \"\"\"Handle successful task completion\"\"\"\n",
    "        task.status = TaskStatus.COMPLETED\n",
    "        task.progress = 1.0\n",
    "        task.result = result.get('result')\n",
    "        \n",
    "        execution_result['tasks_completed'] += 1\n",
    "        \n",
    "        print_plan_step(execution_result['tasks_completed'], task.name, task.description, \"completed\")\n",
    "        \n",
    "        # Update context with task results\n",
    "        self.current_plan.context[f'task_{task.id}_result'] = task.result\n",
    "        \n",
    "        # Record in memory if available\n",
    "        if self.memory_manager:\n",
    "            self.memory_manager.add_experience(\n",
    "                action=task.action,\n",
    "                context=f\"Task: {task.name}\",\n",
    "                outcome=\"Success\",\n",
    "                success=True\n",
    "            )\n",
    "        \n",
    "        logger.info(f\"Task {task.name} completed successfully\")\n",
    "    \n",
    "    async def _handle_task_failure(self, task: Task, error: str, execution_result: Dict):\n",
    "        \"\"\"Handle task failure with retry and recovery logic\"\"\"\n",
    "        task.retry_count += 1\n",
    "        task.error = error\n",
    "        \n",
    "        logger.warning(f\"Task {task.name} failed (attempt {task.retry_count}): {error}\")\n",
    "        \n",
    "        if task.retry_count < task.max_retries:\n",
    "            # Retry the task\n",
    "            task.status = TaskStatus.PENDING\n",
    "            logger.info(f\"Retrying task {task.name} (attempt {task.retry_count + 1})\")\n",
    "            execution_result['error_recoveries'] += 1\n",
    "        else:\n",
    "            # Task has failed permanently\n",
    "            task.status = TaskStatus.FAILED\n",
    "            task.progress = 0.0\n",
    "            execution_result['tasks_failed'] += 1\n",
    "            \n",
    "            print_plan_step(execution_result['tasks_completed'] + execution_result['tasks_failed'], \n",
    "                           task.name, task.description, \"failed\")\n",
    "            \n",
    "            # Record failure in memory\n",
    "            if self.memory_manager:\n",
    "                self.memory_manager.add_experience(\n",
    "                    action=task.action,\n",
    "                    context=f\"Task: {task.name}\",\n",
    "                    outcome=f\"Failed: {error}\",\n",
    "                    success=False\n",
    "                )\n",
    "            \n",
    "            # Check if failure blocks critical path\n",
    "            if task.priority.value >= Priority.HIGH.value:\n",
    "                logger.error(f\"Critical task {task.name} failed - plan may be compromised\")\n",
    "    \n",
    "    async def _monitor_progress(self, plan: Plan, execution_result: Dict):\n",
    "        \"\"\"Monitor plan progress and detect issues\"\"\"\n",
    "        progress = plan.get_progress()\n",
    "        \n",
    "        monitoring_data = {\n",
    "            'timestamp': datetime.now(),\n",
    "            'progress': progress,\n",
    "            'tasks_completed': execution_result['tasks_completed'],\n",
    "            'tasks_failed': execution_result['tasks_failed'],\n",
    "            'tasks_running': len([t for t in plan.tasks.values() if t.status == TaskStatus.RUNNING])\n",
    "        }\n",
    "        \n",
    "        self.monitoring_data.append(monitoring_data)\n",
    "        \n",
    "        # Check for progress issues\n",
    "        if len(self.monitoring_data) > 5:  # Check trend over last 5 measurements\n",
    "            recent_progress = [d['progress'] for d in self.monitoring_data[-5:]]\n",
    "            if all(p <= self.replan_threshold for p in recent_progress[-3:]):\n",
    "                logger.warning(f\"Low progress detected: {progress:.1%}\")\n",
    "    \n",
    "    def _is_plan_blocked(self, plan: Plan) -> bool:\n",
    "        \"\"\"Check if plan execution is blocked\"\"\"\n",
    "        pending_tasks = [t for t in plan.tasks.values() if t.status == TaskStatus.PENDING]\n",
    "        running_tasks = [t for t in plan.tasks.values() if t.status == TaskStatus.RUNNING]\n",
    "        \n",
    "        # Plan is blocked if there are pending tasks but none can start and none are running\n",
    "        if pending_tasks and not running_tasks:\n",
    "            ready_tasks = plan.get_ready_tasks()\n",
    "            return len(ready_tasks) == 0\n",
    "        \n",
    "        return False\n",
    "    \n",
    "    async def _attempt_replan(self, plan: Plan) -> bool:\n",
    "        \"\"\"Attempt to replan when execution is blocked\"\"\"\n",
    "        logger.info(\"Attempting to replan due to execution issues\")\n",
    "        \n",
    "        try:\n",
    "            # Create new plan for remaining goals\n",
    "            remaining_goal = f\"Complete remaining tasks for: {plan.goal}\"\n",
    "            \n",
    "            new_plan = self.replanner.create_plan(\n",
    "                goal=remaining_goal,\n",
    "                context=plan.context\n",
    "            )\n",
    "            \n",
    "            # Merge new tasks into existing plan\n",
    "            for task in new_plan.tasks.values():\n",
    "                if task.id not in plan.tasks:\n",
    "                    plan.add_task(task)\n",
    "            \n",
    "            logger.info(f\"Replanning successful - added {len(new_plan.tasks)} new tasks\")\n",
    "            return True\n",
    "        \n",
    "        except Exception as e:\n",
    "            logger.error(f\"Replanning failed: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def _print_execution_summary(self, plan: Plan, execution_result: Dict):\n",
    "        \"\"\"Print final execution summary\"\"\"\n",
    "        print_section(\"PLAN EXECUTION SUMMARY\", \n",
    "                     f\"Plan: {plan.name}\\nStatus: {execution_result['status'].title()}\")\n",
    "        \n",
    "        print(f\"📊 Execution Statistics:\")\n",
    "        print(f\"  • Total tasks: {len(plan.tasks)}\")\n",
    "        print(f\"  • Completed: {execution_result['tasks_completed']}\")\n",
    "        print(f\"  • Failed: {execution_result['tasks_failed']}\")\n",
    "        print(f\"  • Success rate: {(execution_result['tasks_completed'] / len(plan.tasks) * 100):.1f}%\")\n",
    "        print(f\"  • Duration: {execution_result.get('total_duration', 0):.1f} seconds\")\n",
    "        print(f\"  • Replanning events: {execution_result['replanning_events']}\")\n",
    "        print(f\"  • Error recoveries: {execution_result['error_recoveries']}\")\n",
    "\n",
    "# Create the adaptive executor\n",
    "executor = AdaptivePlanExecutor(\n",
    "    # tool_manager=tool_manager,  # Uncomment if you have tool_manager from Module 3\n",
    "    # memory_manager=memory_manager,  # Uncomment if you have memory_manager from Module 2\n",
    "    replanner=htn_planner\n",
    ")\n",
    "\n",
    "print(\"✅ Adaptive Plan Executor created!\")\n",
    "print(\"⚙️ Features: Monitoring, error recovery, adaptive replanning\")\n",
    "print(\"🔄 Ready to execute complex plans with resilience\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "planning-demo",
   "metadata": {},
   "source": [
    "## 🚀 Comprehensive Planning Demo\n",
    "\n",
    "Let's put everything together with a realistic planning and execution demonstration."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "planning-demo-code",
   "metadata": {},
   "outputs": [],
   "source": [
    "async def comprehensive_planning_demo():\n",
    "    \"\"\"Demonstrate the complete planning and execution system\"\"\"\n",
    "    \n",
    "    print_section(\"COMPREHENSIVE PLANNING DEMONSTRATION\", \n",
    "                 \"Creating and executing a complex multi-step plan\")\n",
    "    \n",
    "    # Define a complex goal\n",
    "    goal = \"Create a comprehensive quarterly business report with analysis and recommendations\"\n",
    "    \n",
    "    # Create context for planning\n",
    "    planning_context = {\n",
    "        'quarter': 'Q3 2024',\n",
    "        'departments': ['Engineering', 'Sales', 'Marketing'],\n",
    "        'report_format': 'executive_summary',\n",
    "        'deadline': (datetime.now() + timedelta(days=7)).isoformat(),\n",
    "        'stakeholders': ['CEO', 'VP Engineering', 'VP Sales']\n",
    "    }\n",
    "    \n",
    "    print(f\"🎯 Goal: {goal}\")\n",
    "    print(f\"📋 Context: {json.dumps(planning_context, indent=2)}\")\n",
    "    \n",
    "    # Step 1: Create plan using HTN planner\n",
    "    print(\"\\n🌲 Creating hierarchical plan...\")\n",
    "    plan = htn_planner.create_plan(goal, planning_context)\n",
    "    \n",
    "    print(f\"✅ Plan created with {len(plan.tasks)} tasks\")\n",
    "    \n",
    "    # Display the plan structure\n",
    "    print(\"\\n📋 Plan Structure:\")\n",
    "    for i, task_id in enumerate(plan.task_order, 1):\n",
    "        task = plan.tasks[task_id]\n",
    "        deps = f\" (depends on: {', '.join(task.dependencies)})\" if task.dependencies else \"\"\n",
    "        duration = f\" [{task.estimated_duration}]\" if task.estimated_duration else \"\"\n",
    "        print(f\"  {i}. {task.name}{duration}{deps}\")\n",
    "        print(f\"     Action: {task.action} | Priority: {task.priority.name}\")\n",
    "    \n",
    "    # Step 2: Validate plan with GOAP\n",
    "    print(\"\\n🎯 Validating plan feasibility with GOAP...\")\n",
    "    \n",
    "    # Set up GOAP world state based on current context\n",
    "    goap_initial_state = {\n",
    "        'has_database_access': True,\n",
    "        'has_analysis_tools': True,\n",
    "        'has_report_template': True,\n",
    "        'has_raw_data': False,\n",
    "        'has_processed_data': False,\n",
    "        'has_analysis': False,\n",
    "        'has_draft_report': False,\n",
    "        'has_final_report': False\n",
    "    }\n",
    "    \n",
    "    goap_goal_state = {'has_final_report': True}\n",
    "    \n",
    "    # Register additional GOAP actions for this domain\n",
    "    goap_planner.register_action(\n",
    "        name=\"extract_raw_data\",\n",
    "        preconditions={'has_database_access': True},\n",
    "        effects={'has_raw_data': True},\n",
    "        cost=2.0\n",
    "    )\n",
    "    \n",
    "    goap_planner.register_action(\n",
    "        name=\"process_data\",\n",
    "        preconditions={'has_raw_data': True, 'has_analysis_tools': True},\n",
    "        effects={'has_processed_data': True},\n",
    "        cost=3.0\n",
    "    )\n",
    "    \n",
    "    goap_planner.register_action(\n",
    "        name=\"create_analysis\",\n",
    "        preconditions={'has_processed_data': True},\n",
    "        effects={'has_analysis': True},\n",
    "        cost=4.0\n",
    "    )\n",
    "    \n",
    "    goap_planner.register_action(\n",
    "        name=\"draft_report\",\n",
    "        preconditions={'has_analysis': True, 'has_report_template': True},\n",
    "        effects={'has_draft_report': True},\n",
    "        cost=3.0\n",
    "    )\n",
    "    \n",
    "    goap_planner.register_action(\n",
    "        name=\"finalize_report\",\n",
    "        preconditions={'has_draft_report': True},\n",
    "        effects={'has_final_report': True},\n",
    "        cost=2.0\n",
    "    )\n",
    "    \n",
    "    goap_planner.set_world_state(goap_initial_state)\n",
    "    goap_action_sequence = goap_planner.plan(goap_goal_state)\n",
    "    \n",
    "    if goap_action_sequence:\n",
    "        print(f\"✅ GOAP validation successful: {len(goap_action_sequence)} actions\")\n",
    "        print(\"   Action sequence:\", \" → \".join(goap_action_sequence))\n",
    "    else:\n",
    "        print(\"❌ GOAP validation failed - plan may not be feasible\")\n",
    "    \n",
    "    # Step 3: Execute the plan\n",
    "    print(\"\\n⚙️ Executing plan with adaptive monitoring...\")\n",
    "    \n",
    "    execution_result = await executor.execute_plan(plan)\n",
    "    \n",
    "    # Step 4: Analyze execution results\n",
    "    print(\"\\n📊 Execution Analysis:\")\n",
    "    \n",
    "    if execution_result['status'] == 'completed':\n",
    "        print(\"🎉 Plan executed successfully!\")\n",
    "        \n",
    "        # Calculate efficiency metrics\n",
    "        total_tasks = len(plan.tasks)\n",
    "        success_rate = execution_result['tasks_completed'] / total_tasks * 100\n",
    "        \n",
    "        estimated_duration = sum(\n",
    "            (task.estimated_duration.total_seconds() if task.estimated_duration else 30)\n",
    "            for task in plan.tasks.values()\n",
    "        )\n",
    "        \n",
    "        actual_duration = execution_result['total_duration']\n",
    "        efficiency = (estimated_duration / actual_duration * 100) if actual_duration > 0 else 100\n",
    "        \n",
    "        print(f\"  📈 Success rate: {success_rate:.1f}%\")\n",
    "        print(f\"  ⏱️ Time efficiency: {efficiency:.1f}%\")\n",
    "        print(f\"  🔄 Adaptations made: {execution_result['replanning_events']}\")\n",
    "        print(f\"  🛠️ Error recoveries: {execution_result['error_recoveries']}\")\n",
    "        \n",
    "    else:\n",
    "        print(f\"❌ Plan execution {execution_result['status']}\")\n",
    "        print(\"🔍 Consider revising the plan or addressing blocking issues\")\n",
    "    \n",
    "    # Step 5: Extract learnings\n",
    "    print(\"\\n🧠 Planning System Learnings:\")\n",
    "    \n",
    "    planning_insights = [\n",
    "        \"HTN decomposition provides structured approach to complex goals\",\n",
    "        \"GOAP validation helps ensure plan feasibility before execution\",\n",
    "        \"Adaptive execution handles real-world uncertainties and failures\",\n",
    "        \"Monitoring enables early detection and correction of issues\",\n",
    "        \"Multi-level planning (strategic → tactical