{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "course-header",
   "metadata": {},
   "source": [
    "# Module 3: Tool Integration and Environment Interaction\n",
    "*Building Agents That Connect to the Real World*\n",
    "\n",
    "**Learning Objectives:**\n",
    "- Connect agents to external APIs, databases, and services\n",
    "- Implement robust error handling and fallback strategies\n",
    "- Create dynamic tool discovery and integration systems\n",
    "- Build agents that can operate in complex, real-world environments\n",
    "\n",
    "**Duration:** 55 minutes\n",
    "\n",
    "**Prerequisites:** Modules 1 & 2 (Agent Foundations, Memory & Learning)\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "tool-integration-intro",
   "metadata": {},
   "source": [
    "## 🌍 Why Tool Integration Matters\n",
    "\n",
    "So far, we've built agents that can reason and remember. But **real agentic power comes from connecting to the external world**. Modern agents need to:\n",
    "\n",
    "### 🔌 Connect to Real Services\n",
    "- **APIs**: REST, GraphQL, WebSocket connections\n",
    "- **Databases**: SQL, NoSQL, vector databases\n",
    "- **Cloud Services**: AWS, Google Cloud, Azure\n",
    "- **Third-party Tools**: Slack, GitHub, Salesforce, etc.\n",
    "\n",
    "### 🛠️ Handle Complex Operations\n",
    "- **File Processing**: Read, write, analyze documents\n",
    "- **Data Analysis**: Query databases, generate reports\n",
    "- **Communication**: Send emails, post messages, make calls\n",
    "- **Automation**: Trigger workflows, schedule tasks\n",
    "\n",
    "### 🏗️ Adapt to Changing Environments\n",
    "- **Dynamic Discovery**: Find and integrate new tools\n",
    "- **Error Recovery**: Handle failures gracefully\n",
    "- **Rate Limiting**: Respect API constraints\n",
    "- **Authentication**: Manage credentials securely\n",
    "\n",
    "---\n",
    "\n",
    "## 🔧 Tool Integration Architecture\n",
    "\n",
    "A robust tool integration system consists of several layers:\n",
    "\n",
    "```\n",
    "┌─────────────────────────────────────┐\n",
    "│           Agent Core                │\n",
    "├─────────────────────────────────────┤\n",
    "│       Tool Manager Layer            │\n",
    "├─────────────────────────────────────┤\n",
    "│      Tool Abstraction Layer         │\n",
    "├─────────────────────────────────────┤\n",
    "│     Connection & Auth Layer         │\n",
    "├─────────────────────────────────────┤\n",
    "│    External Services & APIs         │\n",
    "└─────────────────────────────────────┘\n",
    "```\n",
    "\n",
    "Each layer provides:\n",
    "- **Abstraction** from implementation details\n",
    "- **Error handling** and recovery mechanisms\n",
    "- **Security** and authentication management\n",
    "- **Performance** optimization and caching"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "setup-imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Enhanced imports for tool integration\n",
    "import openai\n",
    "import requests\n",
    "import json\n",
    "import sqlite3\n",
    "import pandas as pd\n",
    "import time\n",
    "import asyncio\n",
    "import aiohttp\n",
    "from datetime import datetime, timedelta\n",
    "from typing import List, Dict, Any, Optional, Union, Callable\n",
    "from dataclasses import dataclass, field\n",
    "from enum import Enum\n",
    "from abc import ABC, abstractmethod\n",
    "import hashlib\n",
    "import os\n",
    "import logging\n",
    "from pathlib import Path\n",
    "import yaml\n",
    "import smtplib\n",
    "from email.mime.text import MIMEText\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "import schedule\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Load environment\n",
    "load_dotenv()\n",
    "\n",
    "# Setup logging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# Helper functions\n",
    "def print_section(title: str, content: str):\n",
    "    \"\"\"Enhanced section formatter with colors\"\"\"\n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"🔧 {title}\")\n",
    "    print(f\"{'='*60}\")\n",
    "    print(content)\n",
    "    print(f\"{'='*60}\\n\")\n",
    "\n",
    "def print_tool_result(tool_name: str, input_data: str, result: str, success: bool = True):\n",
    "    \"\"\"Format tool execution results\"\"\"\n",
    "    status = \"✅\" if success else \"❌\"\n",
    "    print(f\"\\n{status} Tool: {tool_name}\")\n",
    "    print(f\"📥 Input: {input_data}\")\n",
    "    print(f\"📤 Result: {result}\")\n",
    "    print(\"-\" * 40)\n",
    "\n",
    "print(\"✅ Advanced tool integration environment ready!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "tool-base-classes",
   "metadata": {},
   "source": [
    "## 🏗️ Building the Tool Integration Framework\n",
    "\n",
    "Let's create a robust, extensible framework for tool integration that can handle real-world complexity."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "tool-framework",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Tool integration framework with robust error handling\n",
    "\n",
    "class ToolExecutionStatus(Enum):\n",
    "    \"\"\"Possible outcomes of tool execution\"\"\"\n",
    "    SUCCESS = \"success\"\n",
    "    FAILURE = \"failure\"\n",
    "    TIMEOUT = \"timeout\"\n",
    "    RATE_LIMITED = \"rate_limited\"\n",
    "    AUTH_ERROR = \"auth_error\"\n",
    "    RETRY_NEEDED = \"retry_needed\"\n",
    "\n",
    "@dataclass\n",
    "class ToolResult:\n",
    "    \"\"\"Comprehensive result object for tool execution\"\"\"\n",
    "    status: ToolExecutionStatus\n",
    "    data: Any = None\n",
    "    error: Optional[str] = None\n",
    "    execution_time: float = 0.0\n",
    "    metadata: Dict[str, Any] = field(default_factory=dict)\n",
    "    retry_count: int = 0\n",
    "    \n",
    "    @property\n",
    "    def is_success(self) -> bool:\n",
    "        return self.status == ToolExecutionStatus.SUCCESS\n",
    "    \n",
    "    @property\n",
    "    def needs_retry(self) -> bool:\n",
    "        return self.status in [ToolExecutionStatus.TIMEOUT, ToolExecutionStatus.RATE_LIMITED, ToolExecutionStatus.RETRY_NEEDED]\n",
    "\n",
    "@dataclass\n",
    "class ToolConfig:\n",
    "    \"\"\"Configuration for tool behavior\"\"\"\n",
    "    max_retries: int = 3\n",
    "    timeout_seconds: float = 30.0\n",
    "    rate_limit_delay: float = 1.0\n",
    "    cache_results: bool = True\n",
    "    cache_ttl: int = 300  # 5 minutes\n",
    "    auth_required: bool = False\n",
    "    environment: str = \"production\"\n",
    "\n",
    "class BaseTool(ABC):\n",
    "    \"\"\"Abstract base class for all tools with robust error handling\"\"\"\n",
    "    \n",
    "    def __init__(self, name: str, description: str, config: Optional[ToolConfig] = None):\n",
    "        self.name = name\n",
    "        self.description = description\n",
    "        self.config = config or ToolConfig()\n",
    "        self.execution_count = 0\n",
    "        self.success_count = 0\n",
    "        self.cache = {}  # Simple in-memory cache\n",
    "        self.last_execution = None\n",
    "    \n",
    "    async def execute_async(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Execute tool with full error handling and retry logic\"\"\"\n",
    "        start_time = time.time()\n",
    "        self.execution_count += 1\n",
    "        \n",
    "        # Check cache first\n",
    "        if self.config.cache_results:\n",
    "            cache_key = self._generate_cache_key(input_data, kwargs)\n",
    "            cached_result = self._get_cached_result(cache_key)\n",
    "            if cached_result:\n",
    "                cached_result.metadata[\"from_cache\"] = True\n",
    "                return cached_result\n",
    "        \n",
    "        # Execute with retry logic\n",
    "        for attempt in range(self.config.max_retries + 1):\n",
    "            try:\n",
    "                # Rate limiting\n",
    "                if attempt > 0:\n",
    "                    await asyncio.sleep(self.config.rate_limit_delay * attempt)\n",
    "                \n",
    "                # Execute the actual tool logic\n",
    "                result = await self._execute_impl(input_data, **kwargs)\n",
    "                \n",
    "                if result.is_success:\n",
    "                    self.success_count += 1\n",
    "                    execution_time = time.time() - start_time\n",
    "                    result.execution_time = execution_time\n",
    "                    result.metadata[\"attempt\"] = attempt + 1\n",
    "                    \n",
    "                    # Cache successful results\n",
    "                    if self.config.cache_results:\n",
    "                        self._cache_result(cache_key, result)\n",
    "                    \n",
    "                    self.last_execution = datetime.now()\n",
    "                    return result\n",
    "                \n",
    "                elif not result.needs_retry or attempt >= self.config.max_retries:\n",
    "                    result.execution_time = time.time() - start_time\n",
    "                    result.retry_count = attempt\n",
    "                    return result\n",
    "                \n",
    "            except asyncio.TimeoutError:\n",
    "                if attempt >= self.config.max_retries:\n",
    "                    return ToolResult(\n",
    "                        status=ToolExecutionStatus.TIMEOUT,\n",
    "                        error=\"Tool execution timed out after retries\",\n",
    "                        execution_time=time.time() - start_time,\n",
    "                        retry_count=attempt\n",
    "                    )\n",
    "            \n",
    "            except Exception as e:\n",
    "                if attempt >= self.config.max_retries:\n",
    "                    return ToolResult(\n",
    "                        status=ToolExecutionStatus.FAILURE,\n",
    "                        error=f\"Tool execution failed: {str(e)}\",\n",
    "                        execution_time=time.time() - start_time,\n",
    "                        retry_count=attempt\n",
    "                    )\n",
    "        \n",
    "        # Should never reach here, but just in case\n",
    "        return ToolResult(\n",
    "            status=ToolExecutionStatus.FAILURE,\n",
    "            error=\"Unexpected execution path\",\n",
    "            execution_time=time.time() - start_time\n",
    "        )\n",
    "    \n",
    "    def execute(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Synchronous wrapper for async execution\"\"\"\n",
    "        return asyncio.run(self.execute_async(input_data, **kwargs))\n",
    "    \n",
    "    @abstractmethod\n",
    "    async def _execute_impl(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Implement the actual tool logic in subclasses\"\"\"\n",
    "        pass\n",
    "    \n",
    "    def _generate_cache_key(self, input_data: Any, kwargs: Dict) -> str:\n",
    "        \"\"\"Generate a cache key for the input\"\"\"\n",
    "        content = f\"{self.name}:{input_data}:{sorted(kwargs.items())}\"\n",
    "        return hashlib.md5(content.encode()).hexdigest()\n",
    "    \n",
    "    def _get_cached_result(self, cache_key: str) -> Optional[ToolResult]:\n",
    "        \"\"\"Get result from cache if valid\"\"\"\n",
    "        if cache_key in self.cache:\n",
    "            cached_data, timestamp = self.cache[cache_key]\n",
    "            if time.time() - timestamp < self.config.cache_ttl:\n",
    "                return cached_data\n",
    "            else:\n",
    "                del self.cache[cache_key]\n",
    "        return None\n",
    "    \n",
    "    def _cache_result(self, cache_key: str, result: ToolResult):\n",
    "        \"\"\"Cache a successful result\"\"\"\n",
    "        self.cache[cache_key] = (result, time.time())\n",
    "    \n",
    "    def get_stats(self) -> Dict[str, Any]:\n",
    "        \"\"\"Get tool execution statistics\"\"\"\n",
    "        success_rate = (self.success_count / self.execution_count * 100) if self.execution_count > 0 else 0\n",
    "        return {\n",
    "            \"name\": self.name,\n",
    "            \"executions\": self.execution_count,\n",
    "            \"successes\": self.success_count,\n",
    "            \"success_rate\": round(success_rate, 2),\n",
    "            \"cache_size\": len(self.cache),\n",
    "            \"last_execution\": self.last_execution.isoformat() if self.last_execution else None\n",
    "        }\n",
    "\n",
    "print(\"✅ Tool integration framework created!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "database-tool",
   "metadata": {},
   "source": [
    "## 🗄️ Real-World Tool Examples\n",
    "\n",
    "Let's implement several real-world tools that demonstrate different integration patterns:\n",
    "\n",
    "### 1. Database Query Tool\n",
    "Connects to databases and executes queries safely"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "database-tool-impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "class DatabaseTool(BaseTool):\n",
    "    \"\"\"Tool for executing database queries with safety checks\"\"\"\n",
    "    \n",
    "    def __init__(self, db_path: str = \":memory:\"):\n",
    "        super().__init__(\n",
    "            name=\"database_query\",\n",
    "            description=\"Execute SQL queries on database with safety checks\",\n",
    "            config=ToolConfig(cache_results=True, timeout_seconds=10.0)\n",
    "        )\n",
    "        self.db_path = db_path\n",
    "        self._setup_demo_data()\n",
    "    \n",
    "    def _setup_demo_data(self):\n",
    "        \"\"\"Create demo database with sample data\"\"\"\n",
    "        conn = sqlite3.connect(self.db_path)\n",
    "        cursor = conn.cursor()\n",
    "        \n",
    "        # Create tables\n",
    "        cursor.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS employees (\n",
    "            id INTEGER PRIMARY KEY,\n",
    "            name TEXT NOT NULL,\n",
    "            department TEXT,\n",
    "            salary INTEGER,\n",
    "            hire_date DATE\n",
    "        )\n",
    "        \"\"\")\n",
    "        \n",
    "        cursor.execute(\"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS projects (\n",
    "            id INTEGER PRIMARY KEY,\n",
    "            name TEXT NOT NULL,\n",
    "            budget INTEGER,\n",
    "            status TEXT,\n",
    "            manager_id INTEGER,\n",
    "            FOREIGN KEY (manager_id) REFERENCES employees (id)\n",
    "        )\n",
    "        \"\"\")\n",
    "        \n",
    "        # Insert sample data\n",
    "        employees = [\n",
    "            (1, 'Alice Johnson', 'Engineering', 95000, '2022-01-15'),\n",
    "            (2, 'Bob Smith', 'Engineering', 87000, '2022-03-01'),\n",
    "            (3, 'Carol Davis', 'Marketing', 72000, '2021-11-20'),\n",
    "            (4, 'David Wilson', 'Sales', 68000, '2023-02-10'),\n",
    "            (5, 'Eve Brown', 'Engineering', 91000, '2022-08-05')\n",
    "        ]\n",
    "        \n",
    "        cursor.executemany(\n",
    "            \"INSERT OR REPLACE INTO employees VALUES (?, ?, ?, ?, ?)\",\n",
    "            employees\n",
    "        )\n",
    "        \n",
    "        projects = [\n",
    "            (1, 'AI Platform', 500000, 'active', 1),\n",
    "            (2, 'Mobile App', 200000, 'completed', 2),\n",
    "            (3, 'Marketing Campaign', 150000, 'planning', 3)\n",
    "        ]\n",
    "        \n",
    "        cursor.executemany(\n",
    "            \"INSERT OR REPLACE INTO projects VALUES (?, ?, ?, ?, ?)\",\n",
    "            projects\n",
    "        )\n",
    "        \n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "    \n",
    "    async def _execute_impl(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Execute database query with safety checks\"\"\"\n",
    "        query = input_data.strip() if isinstance(input_data, str) else str(input_data)\n",
    "        \n",
    "        # Safety checks\n",
    "        if not self._is_safe_query(query):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Query rejected by safety checks\"\n",
    "            )\n",
    "        \n",
    "        try:\n",
    "            conn = sqlite3.connect(self.db_path)\n",
    "            conn.row_factory = sqlite3.Row  # Enable column access by name\n",
    "            cursor = conn.cursor()\n",
    "            \n",
    "            # Execute query\n",
    "            cursor.execute(query)\n",
    "            \n",
    "            if query.strip().upper().startswith('SELECT'):\n",
    "                # For SELECT queries, return results\n",
    "                rows = cursor.fetchall()\n",
    "                result_data = [dict(row) for row in rows]\n",
    "                \n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.SUCCESS,\n",
    "                    data={\n",
    "                        \"rows\": result_data,\n",
    "                        \"count\": len(result_data),\n",
    "                        \"columns\": [desc[0] for desc in cursor.description] if cursor.description else []\n",
    "                    },\n",
    "                    metadata={\"query_type\": \"SELECT\"}\n",
    "                )\n",
    "            else:\n",
    "                # For other queries, return execution info\n",
    "                conn.commit()\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.SUCCESS,\n",
    "                    data={\n",
    "                        \"rows_affected\": cursor.rowcount,\n",
    "                        \"message\": \"Query executed successfully\"\n",
    "                    },\n",
    "                    metadata={\"query_type\": \"MODIFY\"}\n",
    "                )\n",
    "        \n",
    "        except sqlite3.Error as e:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Database error: {str(e)}\"\n",
    "            )\n",
    "        \n",
    "        finally:\n",
    "            if 'conn' in locals():\n",
    "                conn.close()\n",
    "    \n",
    "    def _is_safe_query(self, query: str) -> bool:\n",
    "        \"\"\"Basic safety checks for SQL queries\"\"\"\n",
    "        query_upper = query.upper().strip()\n",
    "        \n",
    "        # Blocked operations\n",
    "        dangerous_ops = ['DROP', 'DELETE', 'TRUNCATE', 'ALTER', 'CREATE USER', 'GRANT']\n",
    "        \n",
    "        for op in dangerous_ops:\n",
    "            if op in query_upper:\n",
    "                return False\n",
    "        \n",
    "        # Must be a reasonable length\n",
    "        if len(query) > 1000:\n",
    "            return False\n",
    "        \n",
    "        return True\n",
    "\n",
    "# Test the database tool\n",
    "db_tool = DatabaseTool()\n",
    "\n",
    "print(\"🗄️ Testing Database Tool:\")\n",
    "\n",
    "# Test 1: Select query\n",
    "result1 = db_tool.execute(\"SELECT name, department, salary FROM employees WHERE salary > 80000\")\n",
    "print_tool_result(\"Database Query\", \"High salary employees\", \n",
    "                 f\"Found {result1.data['count']} employees\" if result1.is_success else result1.error, \n",
    "                 result1.is_success)\n",
    "\n",
    "if result1.is_success:\n",
    "    for emp in result1.data['rows']:\n",
    "        print(f\"  • {emp['name']}: {emp['department']} - ${emp['salary']:,}\")\n",
    "\n",
    "# Test 2: Aggregation query\n",
    "result2 = db_tool.execute(\"SELECT department, COUNT(*) as count, AVG(salary) as avg_salary FROM employees GROUP BY department\")\n",
    "print_tool_result(\"Database Query\", \"Department statistics\", \n",
    "                 f\"Found {result2.data['count']} departments\" if result2.is_success else result2.error,\n",
    "                 result2.is_success)\n",
    "\n",
    "if result2.is_success:\n",
    "    for dept in result2.data['rows']:\n",
    "        print(f\"  • {dept['department']}: {dept['count']} employees, avg salary ${dept['avg_salary']:,.0f}\")\n",
    "\n",
    "print(f\"\\n📊 Database tool stats: {db_tool.get_stats()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "api-tool",
   "metadata": {},
   "source": [
    "### 2. Web API Integration Tool\n",
    "Handles REST API calls with authentication and rate limiting"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "api-tool-impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "class WebAPITool(BaseTool):\n",
    "    \"\"\"Tool for making HTTP API calls with robust error handling\"\"\"\n",
    "    \n",
    "    def __init__(self, base_url: str = None, api_key: str = None):\n",
    "        super().__init__(\n",
    "            name=\"web_api\",\n",
    "            description=\"Make HTTP requests to web APIs with authentication and error handling\",\n",
    "            config=ToolConfig(\n",
    "                timeout_seconds=15.0,\n",
    "                rate_limit_delay=1.0,\n",
    "                cache_results=True,\n",
    "                auth_required=bool(api_key)\n",
    "            )\n",
    "        )\n",
    "        self.base_url = base_url\n",
    "        self.api_key = api_key\n",
    "        self.session = requests.Session()\n",
    "        \n",
    "        # Setup default headers\n",
    "        if api_key:\n",
    "            self.session.headers.update({'Authorization': f'Bearer {api_key}'})\n",
    "        \n",
    "        self.session.headers.update({\n",
    "            'User-Agent': 'AgenticAI-Tool/1.0',\n",
    "            'Content-Type': 'application/json'\n",
    "        })\n",
    "    \n",
    "    async def _execute_impl(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Execute HTTP request\"\"\"\n",
    "        \n",
    "        # Parse input data\n",
    "        if isinstance(input_data, str):\n",
    "            # Simple URL request\n",
    "            request_config = {\n",
    "                'method': 'GET',\n",
    "                'url': input_data\n",
    "            }\n",
    "        elif isinstance(input_data, dict):\n",
    "            # Detailed request configuration\n",
    "            request_config = input_data\n",
    "        else:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Invalid input format. Provide URL string or request config dict\"\n",
    "            )\n",
    "        \n",
    "        # Extract request parameters\n",
    "        method = request_config.get('method', 'GET').upper()\n",
    "        url = request_config.get('url', '')\n",
    "        headers = request_config.get('headers', {})\n",
    "        params = request_config.get('params', {})\n",
    "        data = request_config.get('data', None)\n",
    "        json_data = request_config.get('json', None)\n",
    "        \n",
    "        # Handle relative URLs\n",
    "        if self.base_url and not url.startswith(('http://', 'https://')):\n",
    "            url = f\"{self.base_url.rstrip('/')}/{url.lstrip('/')}\"\n",
    "        \n",
    "        try:\n",
    "            # Make the request\n",
    "            response = self.session.request(\n",
    "                method=method,\n",
    "                url=url,\n",
    "                headers=headers,\n",
    "                params=params,\n",
    "                data=data,\n",
    "                json=json_data,\n",
    "                timeout=self.config.timeout_seconds\n",
    "            )\n",
    "            \n",
    "            # Handle rate limiting\n",
    "            if response.status_code == 429:\n",
    "                retry_after = response.headers.get('Retry-After', '60')\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.RATE_LIMITED,\n",
    "                    error=f\"Rate limited. Retry after {retry_after} seconds\",\n",
    "                    metadata={'retry_after': int(retry_after)}\n",
    "                )\n",
    "            \n",
    "            # Handle authentication errors\n",
    "            if response.status_code in [401, 403]:\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.AUTH_ERROR,\n",
    "                    error=f\"Authentication failed: {response.status_code}\"\n",
    "                )\n",
    "            \n",
    "            # Parse response\n",
    "            try:\n",
    "                response_data = response.json()\n",
    "            except ValueError:\n",
    "                response_data = response.text\n",
    "            \n",
    "            if response.ok:\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.SUCCESS,\n",
    "                    data={\n",
    "                        'status_code': response.status_code,\n",
    "                        'data': response_data,\n",
    "                        'headers': dict(response.headers)\n",
    "                    },\n",
    "                    metadata={\n",
    "                        'url': url,\n",
    "                        'method': method,\n",
    "                        'content_type': response.headers.get('Content-Type', '')\n",
    "                    }\n",
    "                )\n",
    "            else:\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.FAILURE,\n",
    "                    error=f\"HTTP {response.status_code}: {response_data}\",\n",
    "                    metadata={'status_code': response.status_code}\n",
    "                )\n",
    "        \n",
    "        except requests.exceptions.Timeout:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.TIMEOUT,\n",
    "                error=\"Request timed out\"\n",
    "            )\n",
    "        \n",
    "        except requests.exceptions.RequestException as e:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Request failed: {str(e)}\"\n",
    "            )\n",
    "\n",
    "# Create API tool for testing (we'll simulate responses)\n",
    "api_tool = WebAPITool()\n",
    "\n",
    "print(\"🌐 Testing Web API Tool:\")\n",
    "\n",
    "# For demonstration, we'll test with a public API\n",
    "# Test 1: Simple GET request\n",
    "result1 = api_tool.execute(\"https://httpbin.org/get?test=agent\")\n",
    "print_tool_result(\"Web API\", \"GET request to httpbin\", \n",
    "                 f\"Status: {result1.data['status_code']}\" if result1.is_success else result1.error,\n",
    "                 result1.is_success)\n",
    "\n",
    "# Test 2: POST request with JSON data\n",
    "post_config = {\n",
    "    'method': 'POST',\n",
    "    'url': 'https://httpbin.org/post',\n",
    "    'json': {\n",
    "        'message': 'Hello from agent!',\n",
    "        'timestamp': datetime.now().isoformat()\n",
    "    }\n",
    "}\n",
    "\n",
    "result2 = api_tool.execute(post_config)\n",
    "print_tool_result(\"Web API\", \"POST request with JSON\", \n",
    "                 f\"Status: {result2.data['status_code']}\" if result2.is_success else result2.error,\n",
    "                 result2.is_success)\n",
    "\n",
    "print(f\"\\n📊 API tool stats: {api_tool.get_stats()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "file-tool",
   "metadata": {},
   "source": [
    "### 3. File Processing Tool\n",
    "Handles file operations with security and validation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "file-tool-impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "class FileProcessingTool(BaseTool):\n",
    "    \"\"\"Tool for safe file operations with validation and processing\"\"\"\n",
    "    \n",
    "    def __init__(self, workspace_dir: str = \"./agent_workspace\"):\n",
    "        super().__init__(\n",
    "            name=\"file_processor\",\n",
    "            description=\"Process files with safety checks and validation\",\n",
    "            config=ToolConfig(cache_results=False, timeout_seconds=30.0)\n",
    "        )\n",
    "        self.workspace_dir = Path(workspace_dir)\n",
    "        self.workspace_dir.mkdir(exist_ok=True)\n",
    "        \n",
    "        # Allowed file extensions for security\n",
    "        self.allowed_extensions = {'.txt', '.json', '.csv', '.md', '.yml', '.yaml'}\n",
    "        self.max_file_size = 10 * 1024 * 1024  # 10MB limit\n",
    "    \n",
    "    async def _execute_impl(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Execute file operation\"\"\"\n",
    "        \n",
    "        if not isinstance(input_data, dict):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Input must be a dict with 'operation' and parameters\"\n",
    "            )\n",
    "        \n",
    "        operation = input_data.get('operation', '').lower()\n",
    "        \n",
    "        if operation == 'read':\n",
    "            return await self._read_file(input_data)\n",
    "        elif operation == 'write':\n",
    "            return await self._write_file(input_data)\n",
    "        elif operation == 'analyze':\n",
    "            return await self._analyze_file(input_data)\n",
    "        elif operation == 'list':\n",
    "            return await self._list_files(input_data)\n",
    "        else:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Unknown operation: {operation}. Supported: read, write, analyze, list\"\n",
    "            )\n",
    "    \n",
    "    async def _read_file(self, config: Dict) -> ToolResult:\n",
    "        \"\"\"Read file content safely\"\"\"\n",
    "        filename = config.get('filename', '')\n",
    "        encoding = config.get('encoding', 'utf-8')\n",
    "        \n",
    "        if not filename:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Filename is required for read operation\"\n",
    "            )\n",
    "        \n",
    "        file_path = self.workspace_dir / filename\n",
    "        \n",
    "        # Security checks\n",
    "        if not self._is_safe_path(file_path):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"File path is not safe or not allowed\"\n",
    "            )\n",
    "        \n",
    "        try:\n",
    "            if not file_path.exists():\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.FAILURE,\n",
    "                    error=f\"File not found: {filename}\"\n",
    "                )\n",
    "            \n",
    "            # Check file size\n",
    "            if file_path.stat().st_size > self.max_file_size:\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.FAILURE,\n",
    "                    error=f\"File too large (max {self.max_file_size // 1024 // 1024}MB)\"\n",
    "                )\n",
    "            \n",
    "            with open(file_path, 'r', encoding=encoding) as f:\n",
    "                content = f.read()\n",
    "            \n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.SUCCESS,\n",
    "                data={\n",
    "                    'content': content,\n",
    "                    'filename': filename,\n",
    "                    'size': len(content),\n",
    "                    'lines': len(content.splitlines())\n",
    "                },\n",
    "                metadata={'operation': 'read', 'encoding': encoding}\n",
    "            )\n",
    "        \n",
    "        except UnicodeDecodeError:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Cannot decode file with encoding: {encoding}\"\n",
    "            )\n",
    "        \n",
    "        except Exception as e:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Error reading file: {str(e)}\"\n",
    "            )\n",
    "    \n",
    "    async def _write_file(self, config: Dict) -> ToolResult:\n",
    "        \"\"\"Write content to file safely\"\"\"\n",
    "        filename = config.get('filename', '')\n",
    "        content = config.get('content', '')\n",
    "        encoding = config.get('encoding', 'utf-8')\n",
    "        overwrite = config.get('overwrite', False)\n",
    "        \n",
    "        if not filename or not content:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Both filename and content are required for write operation\"\n",
    "            )\n",
    "        \n",
    "        file_path = self.workspace_dir / filename\n",
    "        \n",
    "        # Security checks\n",
    "        if not self._is_safe_path(file_path):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"File path is not safe or not allowed\"\n",
    "            )\n",
    "        \n",
    "        # Check if file exists and overwrite is not allowed\n",
    "        if file_path.exists() and not overwrite:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"File already exists: {filename}. Set overwrite=True to replace\"\n",
    "            )\n",
    "        \n",
    "        try:\n",
    "            # Create directory if needed\n",
    "            file_path.parent.mkdir(parents=True, exist_ok=True)\n",
    "            \n",
    "            with open(file_path, 'w', encoding=encoding) as f:\n",
    "                f.write(content)\n",
    "            \n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.SUCCESS,\n",
    "                data={\n",
    "                    'filename': filename,\n",
    "                    'bytes_written': len(content.encode(encoding)),\n",
    "                    'lines_written': len(content.splitlines()),\n",
    "                    'created': not file_path.existed_before if hasattr(file_path, 'existed_before') else True\n",
    "                },\n",
    "                metadata={'operation': 'write', 'encoding': encoding}\n",
    "            )\n",
    "        \n",
    "        except Exception as e:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Error writing file: {str(e)}\"\n",
    "            )\n",
    "    \n",
    "    async def _analyze_file(self, config: Dict) -> ToolResult:\n",
    "        \"\"\"Analyze file and provide statistics\"\"\"\n",
    "        filename = config.get('filename', '')\n",
    "        \n",
    "        # First read the file\n",
    "        read_result = await self._read_file({'filename': filename})\n",
    "        if not read_result.is_success:\n",
    "            return read_result\n",
    "        \n",
    "        content = read_result.data['content']\n",
    "        file_path = self.workspace_dir / filename\n",
    "        \n",
    "        # Perform analysis\n",
    "        analysis = {\n",
    "            'filename': filename,\n",
    "            'size_bytes': len(content.encode('utf-8')),\n",
    "            'size_chars': len(content),\n",
    "            'lines': len(content.splitlines()),\n",
    "            'words': len(content.split()),\n",
    "            'extension': file_path.suffix,\n",
    "            'is_empty': len(content.strip()) == 0\n",
    "        }\n",
    "        \n",
    "        # File type specific analysis\n",
    "        if file_path.suffix == '.json':\n",
    "            try:\n",
    "                data = json.loads(content)\n",
    "                analysis['json_valid'] = True\n",
    "                analysis['json_keys'] = len(data) if isinstance(data, dict) else None\n",
    "                analysis['json_type'] = type(data).__name__\n",
    "            except json.JSONDecodeError:\n",
    "                analysis['json_valid'] = False\n",
    "        \n",
    "        elif file_path.suffix == '.csv':\n",
    "            lines = content.splitlines()\n",
    "            if lines:\n",
    "                analysis['csv_columns'] = len(lines[0].split(',')) if lines else 0\n",
    "                analysis['csv_rows'] = len(lines) - 1  # Exclude header\n",
    "        \n",
    "        return ToolResult(\n",
    "            status=ToolExecutionStatus.SUCCESS,\n",
    "            data=analysis,\n",
    "            metadata={'operation': 'analyze'}\n",
    "        )\n",
    "    \n",
    "    async def _list_files(self, config: Dict) -> ToolResult:\n",
    "        \"\"\"List files in workspace\"\"\"\n",
    "        pattern = config.get('pattern', '*')\n",
    "        include_hidden = config.get('include_hidden', False)\n",
    "        \n",
    "        try:\n",
    "            files = []\n",
    "            for file_path in self.workspace_dir.glob(pattern):\n",
    "                if file_path.is_file():\n",
    "                    if not include_hidden and file_path.name.startswith('.'):\n",
    "                        continue\n",
    "                    \n",
    "                    files.append({\n",
    "                        'name': file_path.name,\n",
    "                        'size': file_path.stat().st_size,\n",
    "                        'extension': file_path.suffix,\n",
    "                        'modified': datetime.fromtimestamp(file_path.stat().st_mtime).isoformat()\n",
    "                    })\n",
    "            \n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.SUCCESS,\n",
    "                data={\n",
    "                    'files': files,\n",
    "                    'count': len(files),\n",
    "                    'workspace': str(self.workspace_dir)\n",
    "                },\n",
    "                metadata={'operation': 'list', 'pattern': pattern}\n",
    "            )\n",
    "        \n",
    "        except Exception as e:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Error listing files: {str(e)}\"\n",
    "            )\n",
    "    \n",
    "    def _is_safe_path(self, file_path: Path) -> bool:\n",
    "        \"\"\"Check if file path is safe and allowed\"\"\"\n",
    "        try:\n",
    "            # Resolve path to prevent directory traversal\n",
    "            resolved_path = file_path.resolve()\n",
    "            workspace_resolved = self.workspace_dir.resolve()\n",
    "            \n",
    "            # Check if path is within workspace\n",
    "            if not str(resolved_path).startswith(str(workspace_resolved)):\n",
    "                return False\n",
    "            \n",
    "            # Check file extension\n",
    "            if file_path.suffix.lower() not in self.allowed_extensions:\n",
    "                return False\n",
    "            \n",
    "            return True\n",
    "        \n",
    "        except Exception:\n",
    "            return False\n",
    "\n",
    "# Test the file processing tool\n",
    "file_tool = FileProcessingTool()\n",
    "\n",
    "print(\"📁 Testing File Processing Tool:\")\n",
    "\n",
    "# Test 1: Write a file\n",
    "test_content = \"\"\"# Agent Test File\n",
    "This is a test file created by the file processing tool.\n",
    "\n",
    "Features:\n",
    "- Safe file operations\n",
    "- Content validation\n",
    "- Security checks\n",
    "\n",
    "Timestamp: {}\n",
    "\"\"\".format(datetime.now().isoformat())\n",
    "\n",
    "write_result = file_tool.execute({\n",
    "    'operation': 'write',\n",
    "    'filename': 'test_agent_file.txt',\n",
    "    'content': test_content,\n",
    "    'overwrite': True\n",
    "})\n",
    "\n",
    "print_tool_result(\"File Write\", \"Creating test file\", \n",
    "                 f\"Written {write_result.data['bytes_written']} bytes\" if write_result.is_success else write_result.error,\n",
    "                 write_result.is_success)\n",
    "\n",
    "# Test 2: Read the file back\n",
    "read_result = file_tool.execute({\n",
    "    'operation': 'read',\n",
    "    'filename': 'test_agent_file.txt'\n",
    "})\n",
    "\n",
    "print_tool_result(\"File Read\", \"Reading test file\", \n",
    "                 f\"Read {read_result.data['size']} characters, {read_result.data['lines']} lines\" if read_result.is_success else read_result.error,\n",
    "                 read_result.is_success)\n",
    "\n",
    "# Test 3: Analyze the file\n",
    "analyze_result = file_tool.execute({\n",
    "    'operation': 'analyze',\n",
    "    'filename': 'test_agent_file.txt'\n",
    "})\n",
    "\n",
    "print_tool_result(\"File Analysis\", \"Analyzing test file\", \n",
    "                 f\"Words: {analyze_result.data['words']}, Lines: {analyze_result.data['lines']}\" if analyze_result.is_success else analyze_result.error,\n",
    "                 analyze_result.is_success)\n",
    "\n",
    "# Test 4: List files\n",
    "list_result = file_tool.execute({\n",
    "    'operation': 'list',\n",
    "    'pattern': '*.txt'\n",
    "})\n",
    "\n",
    "print_tool_result(\"File List\", \"Listing .txt files\", \n",
    "                 f\"Found {list_result.data['count']} files\" if list_result.is_success else list_result.error,\n",
    "                 list_result.is_success)\n",
    "\n",
    "print(f\"\\n📊 File tool stats: {file_tool.get_stats()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "guided-exercise-integration",
   "metadata": {},
   "source": [
    "## 💡 Guided Exercise: Build an Email Communication Tool\n",
    "\n",
    "Your task is to create an email tool that can send emails with proper error handling and validation.\n",
    "\n",
    "**Requirements:**\n",
    "1. Validate email addresses\n",
    "2. Handle SMTP connection errors\n",
    "3. Support HTML and plain text emails\n",
    "4. Implement rate limiting for bulk emails"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "guided-exercise-email-tool",
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "from email.mime.text import MIMEText\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "\n",
    "class EmailTool(BaseTool):\n",
    "    \"\"\"Tool for sending emails with validation and error handling\"\"\"\n",
    "    \n",
    "    def __init__(self, smtp_server: str = \"localhost\", smtp_port: int = 587, \n",
    "                 username: str = None, password: str = None):\n",
    "        super().__init__(\n",
    "            name=\"email_sender\",\n",
    "            description=\"Send emails with validation and error handling\",\n",
    "            config=ToolConfig(\n",
    "                timeout_seconds=30.0,\n",
    "                rate_limit_delay=2.0,  # 2 seconds between emails\n",
    "                cache_results=False,   # Don't cache email sends\n",
    "                auth_required=bool(username and password)\n",
    "            )\n",
    "        )\n",
    "        self.smtp_server = smtp_server\n",
    "        self.smtp_port = smtp_port\n",
    "        self.username = username\n",
    "        self.password = password\n",
    "        self.sent_count = 0\n",
    "    \n",
    "    async def _execute_impl(self, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"\n",
    "        Send email with comprehensive validation and error handling.\n",
    "        \n",
    "        YOUR TASK: Complete this implementation with:\n",
    "        1. Email address validation\n",
    "        2. Message construction\n",
    "        3. SMTP connection and sending\n",
    "        4. Proper error handling\n",
    "        \"\"\"\n",
    "        \n",
    "        if not isinstance(input_data, dict):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Input must be a dict with email parameters\"\n",
    "            )\n",
    "        \n",
    "        ### START CODE HERE ###\n",
    "        \n",
    "        # Step 1: Extract and validate email parameters\n",
    "        to_email = input_data.get('to', '')\n",
    "        from_email = input_data.get('from', self.username or 'agent@example.com')\n",
    "        subject = input_data.get('subject', '')\n",
    "        body = input_data.get('body', '')\n",
    "        html_body = input_data.get('html_body', None)\n",
    "        \n",
    "        # YOUR CODE: Validate required fields\n",
    "        if not to_email or not subject or not body:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=\"Missing required fields: to, subject, and body are required\"\n",
    "            )\n",
    "        \n",
    "        # YOUR CODE: Validate email addresses using regex\n",
    "        email_pattern = # YOUR REGEX PATTERN\n",
    "        \n",
    "        if not re.match(email_pattern, to_email):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Invalid recipient email address: {to_email}\"\n",
    "            )\n",
    "        \n",
    "        if not re.match(email_pattern, from_email):\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Invalid sender email address: {from_email}\"\n",
    "            )\n",
    "        \n",
    "        # Step 2: Construct email message\n",
    "        # YOUR CODE: Create MIMEMultipart message\n",
    "        msg = MIMEMultipart('alternative')\n",
    "        msg['Subject'] = # YOUR CODE\n",
    "        msg['From'] = # YOUR CODE\n",
    "        msg['To'] = # YOUR CODE\n",
    "        \n",
    "        # YOUR CODE: Add plain text body\n",
    "        text_part = MIMEText(# YOUR CODE, 'plain')\n",
    "        msg.attach(text_part)\n",
    "        \n",
    "        # YOUR CODE: Add HTML body if provided\n",
    "        if html_body:\n",
    "            html_part = # YOUR CODE: Create HTML part\n",
    "            msg.attach(html_part)\n",
    "        \n",
    "        # Step 3: Send email (simulated for this exercise)\n",
    "        try:\n",
    "            # In a real implementation, you would:\n",
    "            # 1. Connect to SMTP server\n",
    "            # 2. Authenticate if needed\n",
    "            # 3. Send the message\n",
    "            # 4. Handle various SMTP errors\n",
    "            \n",
    "            # For this exercise, we'll simulate the sending\n",
    "            # YOUR CODE: Simulate email sending logic\n",
    "            success = True  # Simulate successful sending\n",
    "            \n",
    "            if success:\n",
    "                self.sent_count += 1\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.SUCCESS,\n",
    "                    data={\n",
    "                        'message': 'Email sent successfully',\n",
    "                        'to': to_email,\n",
    "                        'from': from_email,\n",
    "                        'subject': subject,\n",
    "                        'sent_count': self.sent_count\n",
    "                    },\n",
    "                    metadata={\n",
    "                        'smtp_server': self.smtp_server,\n",
    "                        'has_html': bool(html_body)\n",
    "                    }\n",
    "                )\n",
    "            else:\n",
    "                return ToolResult(\n",
    "                    status=ToolExecutionStatus.FAILURE,\n",
    "                    error=\"Failed to send email\"\n",
    "                )\n",
    "        \n",
    "        except Exception as e:\n",
    "            # YOUR CODE: Handle different types of email errors\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Email sending failed: {str(e)}\"\n",
    "            )\n",
    "        \n",
    "        ### END CODE HERE ###\n",
    "    \n",
    "    def _validate_email(self, email: str) -> bool:\n",
    "        \"\"\"Validate email address format\"\"\"\n",
    "        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'\n",
    "        return re.match(pattern, email) is not None\n",
    "\n",
    "# Test your email tool implementation\n",
    "email_tool = EmailTool(\n",
    "    smtp_server=\"smtp.example.com\",\n",
    "    username=\"agent@example.com\",\n",
    "    password=\"password123\"\n",
    ")\n",
    "\n",
    "print(\"📧 Testing Email Tool:\")\n",
    "\n",
    "# Test 1: Valid email\n",
    "email_config = {\n",
    "    'to': 'user@example.com',\n",
    "    'subject': 'Test Email from Agent',\n",
    "    'body': 'This is a test email sent by the agentic system.',\n",
    "    'html_body': '<h1>Test Email</h1><p>This is a <b>test email</b> sent by the agentic system.</p>'\n",
    "}\n",
    "\n",
    "result1 = email_tool.execute(email_config)\n",
    "print_tool_result(\"Email Send\", \"Valid email test\", \n",
    "                 result1.data['message'] if result1.is_success else result1.error,\n",
    "                 result1.is_success)\n",
    "\n",
    "# Test 2: Invalid email address\n",
    "invalid_email_config = {\n",
    "    'to': 'invalid-email',\n",
    "    'subject': 'Test Email',\n",
    "    'body': 'This should fail due to invalid email.'\n",
    "}\n",
    "\n",
    "result2 = email_tool.execute(invalid_email_config)\n",
    "print_tool_result(\"Email Send\", \"Invalid email test\", \n",
    "                 result2.data['message'] if result2.is_success else result2.error,\n",
    "                 result2.is_success)\n",
    "\n",
    "print(f\"\\n📊 Email tool stats: {email_tool.get_stats()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "solution-reveal-email",
   "metadata": {},
   "source": [
    "### 🔍 Solution Reveal - Email Tool\n",
    "\n",
    "Here's the complete solution for the email tool:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "solution-email",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION - Email Tool Implementation\n",
    "\"\"\"\n",
    "Complete _execute_impl method:\n",
    "\n",
    "# Email validation regex\n",
    "email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'\n",
    "\n",
    "# Message construction\n",
    "msg['Subject'] = subject\n",
    "msg['From'] = from_email\n",
    "msg['To'] = to_email\n",
    "\n",
    "# Plain text part\n",
    "text_part = MIMEText(body, 'plain')\n",
    "\n",
    "# HTML part\n",
    "if html_body:\n",
    "    html_part = MIMEText(html_body, 'html')\n",
    "    msg.attach(html_part)\n",
    "\n",
    "# Real SMTP implementation would include:\n",
    "# server = smtplib.SMTP(self.smtp_server, self.smtp_port)\n",
    "# server.starttls()\n",
    "# server.login(self.username, self.password)\n",
    "# server.send_message(msg)\n",
    "# server.quit()\n",
    "\"\"\"\n",
    "\n",
    "print(\"💡 Solution revealed! Key points:\")\n",
    "print(\"  • Email validation using regex\")\n",
    "print(\"  • MIMEMultipart for complex emails\")\n",
    "print(\"  • Proper error handling for SMTP\")\n",
    "print(\"  • Rate limiting between sends\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "tool-manager",
   "metadata": {},
   "source": [
    "## 🎛️ Advanced Tool Management System\n",
    "\n",
    "Now let's create a sophisticated tool manager that can dynamically discover, load, and coordinate multiple tools."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "tool-manager-impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ToolManager:\n",
    "    \"\"\"Advanced tool management system with dynamic discovery and coordination\"\"\"\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.tools: Dict[str, BaseTool] = {}\n",
    "        self.tool_usage_stats = defaultdict(int)\n",
    "        self.tool_success_rates = defaultdict(list)\n",
    "        self.tool_dependencies = {}  # Tool dependency graph\n",
    "        self.tool_categories = defaultdict(list)\n",
    "    \n",
    "    def register_tool(self, tool: BaseTool, category: str = \"general\") -> bool:\n",
    "        \"\"\"Register a new tool with the manager\"\"\"\n",
    "        try:\n",
    "            if tool.name in self.tools:\n",
    "                logger.warning(f\"Tool {tool.name} already registered, overwriting\")\n",
    "            \n",
    "            self.tools[tool.name] = tool\n",
    "            self.tool_categories[category].append(tool.name)\n",
    "            \n",
    "            logger.info(f\"Registered tool: {tool.name} in category: {category}\")\n",
    "            return True\n",
    "        \n",
    "        except Exception as e:\n",
    "            logger.error(f\"Failed to register tool {tool.name}: {str(e)}\")\n",
    "            return False\n",
    "    \n",
    "    def execute_tool(self, tool_name: str, input_data: Any, **kwargs) -> ToolResult:\n",
    "        \"\"\"Execute a tool with comprehensive logging and stats tracking\"\"\"\n",
    "        if tool_name not in self.tools:\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Tool not found: {tool_name}\"\n",
    "            )\n",
    "        \n",
    "        tool = self.tools[tool_name]\n",
    "        self.tool_usage_stats[tool_name] += 1\n",
    "        \n",
    "        logger.info(f\"Executing tool: {tool_name} with input: {str(input_data)[:100]}\")\n",
    "        \n",
    "        try:\n",
    "            result = tool.execute(input_data, **kwargs)\n",
    "            \n",
    "            # Track success rate\n",
    "            self.tool_success_rates[tool_name].append(result.is_success)\n",
    "            \n",
    "            # Keep only last 100 results for success rate calculation\n",
    "            if len(self.tool_success_rates[tool_name]) > 100:\n",
    "                self.tool_success_rates[tool_name] = self.tool_success_rates[tool_name][-100:]\n",
    "            \n",
    "            logger.info(f\"Tool {tool_name} executed with status: {result.status.value}\")\n",
    "            return result\n",
    "        \n",
    "        except Exception as e:\n",
    "            logger.error(f\"Unexpected error executing tool {tool_name}: {str(e)}\")\n",
    "            return ToolResult(\n",
    "                status=ToolExecutionStatus.FAILURE,\n",
    "                error=f\"Unexpected error: {str(e)}\"\n",
    "            )\n",
    "    \n",
    "    def execute_workflow(self, workflow_steps: List[Dict]) -> List[ToolResult]:\n",
    "        \"\"\"Execute a series of tool operations as a workflow\"\"\"\n",
    "        results = []\n",
    "        context = {}  # Shared context between steps\n",
    "        \n",
    "        for i, step in enumerate(workflow_steps):\n",
    "            tool_name = step.get('tool')\n",
    "            input_data = step.get('input')\n",
    "            use_previous_output = step.get('use_previous_output', False)\n",
    "            condition = step.get('condition', None)\n",
    "            \n",
    "            # Check condition if specified\n",
    "            if condition and not self._evaluate_condition(condition, context, results):\n",
    "                logger.info(f\"Skipping step {i} due to condition: {condition}\")\n",
    "                continue\n",
    "            \n",
    "            # Use previous result as input if specified\n",
    "            if use_previous_output and results:\n",
    "                previous_result = results[-1]\n",
    "                if previous_result.is_success:\n",
    "                    input_data = previous_result.data\n",
    "                else:\n",
    "                    logger.error(f\"Cannot use previous output - previous step failed\")\n",
    "                    break\n",
    "            \n",
    "            # Execute the tool\n",
    "            result = self.execute_tool(tool_name, input_data)\n",
    "            results.append(result)\n",
    "            \n",
    "            # Update context\n",
    "            context[f'step_{i}_result'] = result\n",
    "            context[f'step_{i}_success'] = result.is_success\n",
    "            \n",
    "            # Stop on failure if not configured to continue\n",
    "            if not result.is_success and not step.get('continue_on_failure', False):\n",
    "                logger.error(f\"Workflow stopped at step {i} due to failure\")\n",
    "                break\n",
    "        \n",
    "        return results\n",
    "    \n",
    "    def get_tool_recommendations(self, task_description: str, limit: int = 3) -> List[str]:\n",
    "        \"\"\"Recommend tools based on task description and performance history\"\"\"\n",
    "        recommendations = []\n",
    "        task_lower = task_description.lower()\n",
    "        \n",
    "        # Score tools based on relevance and performance\n",
    "        tool_scores = {}\n",
    "        \n",
    "        for tool_name, tool in self.tools.items():\n",
    "            score = 0.0\n",
    "            \n",
    "            # Relevance score based on description\n",
    "            description_words = tool.description.lower().split()\n",
    "            task_words = task_lower.split()\n",
    "            \n",
    "            common_words = set(description_words) & set(task_words)\n",
    "            relevance_score = len(common_words) / max(len(task_words), 1)\n",
    "            score += relevance_score * 10\n",
    "            \n",
    "            # Performance score\n",
    "            if tool_name in self.tool_success_rates:\n",
    "                success_rate = sum(self.tool_success_rates[tool_name]) / len(self.tool_success_rates[tool_name])\n",
    "                score += success_rate * 5\n",
    "            \n",
    "            # Usage frequency bonus (popular tools)\n",
    "            usage_bonus = min(self.tool_usage_stats[tool_name] / 10, 2.0)\n",
    "            score += usage_bonus\n",
    "            \n",
    "            tool_scores[tool_name] = score\n",
    "        \n",
    "        # Sort by score and return top recommendations\n",
    "        sorted_tools = sorted(tool_scores.items(), key=lambda x: x[1], reverse=True)\n",
    "        return [tool_name for tool_name, _ in sorted_tools[:limit]]\n",
    "    \n",
    "    def get_comprehensive_stats(self) -> Dict[str, Any]:\n",
    "        \"\"\"Get comprehensive statistics about all tools\"\"\"\n",
    "        stats = {\n",
    "            'total_tools': len(self.tools),\n",
    "            'total_executions': sum(self.tool_usage_stats.values()),\n",
    "            'categories': dict(self.tool_categories),\n",
    "            'tool_stats': {}\n",
    "        }\n",
    "        \n",
    "        for tool_name, tool in self.tools.items():\n",
    "            tool_stats = tool.get_stats()\n",
    "            \n",
    "            # Add success rate from manager tracking\n",
    "            if tool_name in self.tool_success_rates:\n",
    "                recent_successes = self.tool_success_rates[tool_name]\n",
    "                success_rate = (sum(recent_successes) / len(recent_successes)) * 100\n",
    "                tool_stats['recent_success_rate'] = round(success_rate, 2)\n",
    "            \n",
    "            stats['tool_stats'][tool_name] = tool_stats\n",
    "        \n",
    "        return stats\n",
    "    \n",
    "    def _evaluate_condition(self, condition: str, context: Dict, results: List[ToolResult]) -> bool:\n",
    "        \"\"\"Evaluate a simple condition for workflow control\"\"\"\n",
    "        # Simple condition evaluation - in production, use a proper expression evaluator\n",
    "        if condition == \"previous_success\" and results:\n",
    "            return results[-1].is_success\n",
    "        elif condition == \"previous_failure\" and results:\n",
    "            return not results[-1].is_success\n",
    "        else:\n",
    "            return True  # Default to true for unknown conditions\n",
    "\n",
    "# Create and configure the tool manager\n",
    "tool_manager = ToolManager()\n",
    "\n",
    "# Register all our tools\n",
    "tool_manager.register_tool(db_tool, \"data\")\n",
    "tool_manager.register_tool(api_tool, \"communication\")\n",
    "tool_manager.register_tool(file_tool, \"file_system\")\n",
    "tool_manager.register_tool(email_tool, \"communication\")\n",
    "\n",
    "print(\"🎛️ Tool Manager created and configured!\")\n",
    "print(f\"📊 Registered {len(tool_manager.tools)} tools across {len(tool_manager.tool_categories)} categories\")\n",
    "\n",
    "# Display tool categories\n",
    "for category, tools in tool_manager.tool_categories.items():\n",
    "    print(f\"  📁 {category}: {', '.join(tools)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "workflow-example",
   "metadata": {},
   "source": [
    "## 🔄 Hands-On Exercise: Complex Workflow Integration\n",
    "\n",
    "Let's test our tool integration system with a complex, multi-step workflow that demonstrates real-world agent capabilities."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "workflow-demo",
   "metadata": {},
   "outputs": [],
   "source": [
    "def demo_complex_workflow():\n",
    "    \"\"\"Demonstrate a complex workflow using multiple integrated tools\"\"\"\n",
    "    \n",
    "    print_section(\"COMPLEX WORKFLOW DEMONSTRATION\", \n",
    "                 \"Executing a multi-step data analysis and reporting workflow\")\n",
    "    \n",
    "    # Define a complex workflow: Data Analysis → Report Generation → Email Notification\n",
    "    workflow_steps = [\n",
    "        {\n",
    "            'tool': 'database_query',\n",
    "            'input': 'SELECT department, COUNT(*) as employee_count, AVG(salary) as avg_salary, MAX(salary) as max_salary FROM employees GROUP BY department ORDER BY avg_salary DESC',\n",
    "            'description': 'Query employee statistics by department'\n",
    "        },\n",
    "        {\n",
    "            'tool': 'file_processor',\n",
    "            'input': {\n",
    "                'operation': 'write',\n",
    "                'filename': 'department_analysis.json',\n",
    "                'content': '',  # Will be populated with query results\n",
    "                'overwrite': True\n",
    "            },\n",
    "            'description': 'Save analysis results to file',\n",
    "            'use_previous_output': True\n",
    "        },\n",
    "        {\n",
    "            'tool': 'file_processor',\n",
    "            'input': {\n",
    "                'operation': 'write',\n",
    "                'filename': 'department_report.txt',\n",
    "                'content': '',  # Will be generated based on analysis\n",
    "                'overwrite': True\n",
    "            },\n",
    "            'description': 'Generate human-readable report'\n",
    "        },\n",
    "        {\n",
    "            'tool': 'email_sender',\n",
    "            'input': {\n",
    "                'to': 'manager@company.com',\n",
    "                'subject': 'Department Analysis Report - ' + datetime.now().strftime('%Y-%m-%d'),\n",
    "                'body': 'Please find the attached department analysis report.',\n",
    "                'html_body': '<h2>Department Analysis Report</h2><p>The analysis has been completed. Please review the attached findings.</p>'\n",
    "            },\n",
    "            'description': 'Send report notification email',\n",
    "            'condition': 'previous_success'\n",
    "        }\n",
    "    ]\n",
    "    \n",
    "    # Execute the workflow step by step with detailed logging\n",
    "    print(\"🚀 Starting workflow execution...\\n\")\n",
    "    \n",
    "    # Step 1: Database Query\n",
    "    print(\"Step 1: Querying employee database...\")\n",
    "    db_result = tool_manager.execute_tool('database_query', workflow_steps[0]['input'])\n",
    "    \n",
    "    if db_result.is_success:\n",
    "        print(f\"✅ Found data for {db_result.data['count']} departments\")\n",
    "        \n",
    "        # Display the results\n",
    "        for dept_data in db_result.data['rows']:\n",
    "            print(f\"  📊 {dept_data['department']}: {dept_data['employee_count']} employees, \"\n",
    "                  f\"avg salary ${dept_data['avg_salary']:,.0f}, max ${dept_data['max_salary']:,}\")\n",
    "        \n",
    "        # Step 2: Save raw data to JSON file\n",
    "        print(\"\\nStep 2: Saving analysis data to file...\")\n",
    "        json_content = json.dumps(db_result.data, indent=2)\n",
    "        \n",
    "        file_save_config = workflow_steps[1]['input'].copy()\n",
    "        file_save_config['content'] = json_content\n",
    "        \n",
    "        save_result = tool_manager.execute_tool('file_processor', file_save_config)\n",
    "        \n",
    "        if save_result.is_success:\n",
    "            print(f\"✅ Saved {save_result.data['bytes_written']} bytes to {save_result.data['filename']}\")\n",
    "            \n",
    "            # Step 3: Generate human-readable report\n",
    "            print(\"\\nStep 3: Generating report...\")\n",
    "            \n",
    "            report_content = f\"\"\"# Department Analysis Report\n",
    "Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
    "\n",
    "## Summary\n",
    "Total departments analyzed: {db_result.data['count']}\n",
    "\n",
    "## Department Breakdown\n",
    "\"\"\"\n",
    "            \n",
    "            for dept_data in db_result.data['rows']:\n",
    "                report_content += f\"\"\"\n",
    "### {dept_data['department']} Department\n",
    "- Employees: {dept_data['employee_count']}\n",
    "- Average Salary: ${dept_data['avg_salary']:,.2f}\n",
    "- Highest Salary: ${dept_data['max_salary']:,}\n",
    "\"\"\"\n",
    "            \n",
    "            # Find highest and lowest performing departments\n",
    "            sorted_depts = sorted(db_result.data['rows'], key=lambda x: x['avg_salary'], reverse=True)\n",
    "            \n",
    "            report_content += f\"\"\"\n",
    "## Analysis\n",
    "- Highest paying department: {sorted_depts[0]['department']} (${sorted_depts[0]['avg_salary']:,.2f} avg)\n",
    "- Lowest paying department: {sorted_depts[-1]['department']} (${sorted_depts[-1]['avg_salary']:,.2f} avg)\n",
    "- Salary range: ${sorted_depts[-1]['avg_salary']:,.2f} - ${sorted_depts[0]['avg_salary']:,.2f}\n",
    "\n",
    "## Recommendations\n",
    "1. Review compensation structure for {sorted_depts[-1]['department']} department\n",
    "2. Consider {sorted_depts[0]['department']} best practices for other departments\n",
    "3. Regular salary benchmarking recommended\n",
    "\"\"\"\n",
    "            \n",
    "            report_save_config = workflow_steps[2]['input'].copy()\n",
    "            report_save_config['content'] = report_content\n",
    "            \n",
    "            report_result = tool_manager.execute_tool('file_processor', report_save_config)\n",
    "            \n",
    "            if report_result.is_success:\n",
    "                print(f\"✅ Generated report: {report_result.data['filename']} ({report_result.data['lines_written']} lines)\")\n",
    "                \n",
    "                # Step 4: Send notification email\n",
    "                print(\"\\nStep 4: Sending notification email...\")\n",
    "                \n",
    "                email_config = workflow_steps[3]['input'].copy()\n",
    "                email_config['body'] += f\"\\n\\nReport files generated:\\n- {file_save_config['filename']}\\n- {report_save_config['filename']}\"\n",
    "                \n",
    "                email_result = tool_manager.execute_tool('email_sender', email_config)\n",
    "                \n",
    "                if email_result.is_success:\n",
    "                    print(f\"✅ Email sent to {email_result.data['to']}\")\n",
    "                    print(\"\\n🎉 Workflow completed successfully!\")\n",
    "                else:\n",
    "                    print(f\"❌ Email failed: {email_result.error}\")\n",
    "            else:\n",
    "                print(f\"❌ Report generation failed: {report_result.error}\")\n",
    "        else:\n",
    "            print(f\"❌ File save failed: {save_result.error}\")\n",
    "    else:\n",
    "        print(f\"❌ Database query failed: {db_result.error}\")\n",
    "    \n",
    "    # Display comprehensive tool statistics\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"📊 WORKFLOW EXECUTION STATISTICS\")\n",
    "    print(\"=\"*60)\n",
    "    \n",
    "    stats = tool_manager.get_comprehensive_stats()\n",
    "    \n",
    "    print(f\"Total tools: {stats['total_tools']}\")\n",
    "    print(f\"Total executions: {stats['total_executions']}\")\n",
    "    \n",
    "    print(\"\\n🔧 Tool Performance:\")\n",
    "    for tool_name, tool_stats in stats['tool_stats'].items():\n",
    "        success_rate = tool_stats.get('recent_success_rate', tool_stats.get('success_rate', 0))\n",
    "        print(f\"  • {tool_name}: {tool_stats['executions']} runs, {success_rate}% success rate\")\n",
    "    \n",
    "    return stats\n",
    "\n",
    "# Execute the complex workflow demonstration\n",
    "workflow_stats = demo_complex_workflow()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "tool-recommendations",
   "metadata": {},
   "source": [
    "## 🎯 Intelligent Tool Recommendations\n",
    "\n",
    "Let's test the tool recommendation system with different types of tasks."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "recommendation-demo",
   "metadata": {},
   "outputs": [],
   "source": [
    "def test_tool_recommendations():\n",
    "    \"\"\"Test the intelligent tool recommendation system\"\"\"\n",
    "    \n",
    "    print_section(\"INTELLIGENT TOOL RECOMMENDATIONS\", \n",
    "                 \"Testing AI-powered tool selection for different tasks\")\n",
    "    \n",
    "    test_tasks = [\n",
    "        \"I need to send an email to the team about project updates\",\n",
    "        \"Analyze employee data and find trends in salary by department\",\n",
    "        \"Save the current analysis results to a file for later review\",\n",
    "        \"Get weather information from an external API\",\n",
    "        \"Create a report document with our findings\",\n",
    "        \"Query the database to find all employees in engineering\"\n",
    "    ]\n",
    "    \n",
    "    for i, task in enumerate(test_tasks, 1):\n",
    "        print(f\"\\n🎯 Task {i}: {task}\")\n",
    "        \n",
    "        recommendations = tool_manager.get_tool_recommendations(task, limit=3)\n",
    "        \n",
    "        print(\"📋 Recommended tools:\")\n",
    "        for j, tool_name in enumerate(recommendations, 1):\n",
    "            tool = tool_manager.tools[tool_name]\n",
    "            print(f\"  {j}. {tool_name}: {tool.description}\")\n",
    "        \n",
    "        if not recommendations:\n",
    "            print(\"  ⚠️ No specific recommendations - consider adding more specialized tools\")\n",
    "    \n",
    "    print(\"\\n💡 Tool recommendation system helps agents automatically select the best tools for each task!\")\n",
    "\n",
    "test_tool_recommendations()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "knowledge-check-module3",
   "metadata": {},
   "source": [
    "## 📝 Module 3 Knowledge Check\n",
    "\n",
    "Test your understanding of tool integration and environment interaction:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "knowledge-check-code-module3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def module3_knowledge_check():\n",
    "    \"\"\"Knowledge check for Module 3 concepts\"\"\"\n",
    "    \n",
    "    questions = [\n",
    "        {\n",
    "            \"question\": \"What are the key layers in a robust tool integration architecture?\",\n",
    "            \"options\": [\n",
    "                \"A) Input, Process, Output\",\n",
    "                \"B) Agent Core, Tool Manager, Tool Abstraction, Connection & Auth, External Services\",\n",
    "                \"C) Database, API, File System\",\n",
    "                \"D) Local, Remote, Cloud\"\n",
    "            ],\n",
    "            \"correct\": \"B\",\n",
    "            \"explanation\": \"Each layer provides specific functionality: abstraction, error handling, security, and performance optimization.\"\n",
    "        },\n",
    "        {\n",
    "            \"question\": \"Why is error handling crucial in tool integration?\",\n",
    "            \"options\": [\n",
    "                \"A) To make code look professional\",\n",
    "                \"B) External services can fail, have rate limits, authentication issues, and network problems\",\n",
    "                \"C) It's required by programming standards\",\n",
    "                \"D) To slow down the system\"\n",
    "            ],\n",
    "            \"correct\": \"B\",\n",
    "            \"explanation\": \"Real-world systems must handle failures gracefully with retries, fallbacks, and proper error reporting.\"\n",
    "        },\n",
    "        {\n",
    "            \"question\": \"What makes a tool 'intelligent' in an agentic system?\",\n",
    "            \"options\": [\n",
    "                \"A) Using machine learning algorithms\",\n",
    "                \"B) Learning from usage patterns, adapting behavior, and improving over time\",\n",
    "                \"C) Having a nice user interface\",\n",
    "                \"D) Being written in Python\"\n",
    "            ],\n",
    "            \"correct\": \"B\",\n",
    "            \"explanation\": \"Intelligent tools learn from experience, adapt to usage patterns, and optimize their behavior based on outcomes.\"\n",
    "        },\n",
    "        {\n",
    "            \"question\": \"What is the purpose of workflow orchestration in tool integration?\",\n",
    "            \"options\": [\n",
    "                \"A) To make tools run faster\",\n",
    "                \"B) To coordinate multiple tools in sequence, handle dependencies, and manage complex multi-step processes\",\n",
    "                \"C) To reduce memory usage\",\n",
    "                \"D) To create pretty diagrams\"\n",
    "            ],\n",
    "            \"correct\": \"B\",\n",
    "            \"explanation\": \"Workflow orchestration enables complex tasks by coordinating tool execution, managing data flow, and handling conditional logic.\"\n",
    "        }\n",
    "    ]\n",
    "    \n",
    "    print(\"📝 MODULE 3 KNOWLEDGE CHECK\")\n",
    "    print(\"=\" * 40)\n",
    "    \n",
    "    for i, q in enumerate(questions, 1):\n",
    "        print(f\"\\nQuestion {i}: {q['question']}\")\n",
    "        for option in q['options']:\n",
    "            print(f\"  {option}\")\n",
    "        \n",
    "        print(f\"\\n✅ Correct Answer: {q['correct']}\")\n",
    "        print(f\"💡 Explanation: {q['explanation']}\")\n",
    "    \n",
    "    print(f\"\\n🎯 Knowledge check complete!\")\n",
    "    print(f\"🔧 You now understand how to build robust, real-world tool integration systems!\")\n",
    "\n",
    "module3_knowledge_check()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "module3-summary",
   "metadata": {},
   "source": [
    "## 🎯 Module 3 Summary\n",
    "\n",
    "Outstanding work! You've built a comprehensive tool integration system that can handle real-world complexity. Let's review your achievements:\n",
    "\n",
    "### ✅ What You Built:\n",
    "- **Robust Tool Framework** with comprehensive error handling\n",
    "- **Database Integration Tool** with safety checks and query validation\n",
    "- **Web API Tool** with authentication, rate limiting, and retry logic\n",
    "- **File Processing Tool** with security validation and multiple operations\n",
    "- **Email Communication Tool** with validation and SMTP handling\n",
    "- **Advanced Tool Manager** with dynamic discovery and workflow orchestration\n",
    "- **Intelligent Recommendation System** for automatic tool selection\n",
    "\n",
    "### 🧠 Key Concepts Mastered:\n",
    "- **Tool Architecture**: Layered design with abstraction and error handling\n",
    "- **Error Resilience**: Retry logic, timeouts, and graceful degradation\n",
    "- **Security Patterns**: Input validation, path traversal protection, safe operations\n",
    "- **Performance Optimization**: Caching, rate limiting, connection pooling\n",
    "- **Workflow Orchestration**: Multi-step processes with conditional execution\n",
    "- **Dynamic Tool Management**: Registration, discovery, and recommendation systems\n",
    "\n",
    "### 🚀 Next Steps:\n",
    "In Module 4, you'll learn to:\n",
    "- Implement sophisticated planning algorithms\n",
    "- Break down complex goals into actionable steps\n",
    "- Create self-correcting planning mechanisms\n",
    "- Build adaptive goal decomposition systems\n",
    "\n",
    "### 💪 Challenge Exercises (Optional):\n",
    "Before Module 4, try:\n",
    "1. Implementing authentication tokens for API tools\n",
    "2. Creating a webhook listener tool for real-time events\n",
    "3. Building a distributed tool execution system\n",
    "4. Adding tool versioning and rollback capabilities"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "module3-progress",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Final Module 3 Progress Summary\n",
    "def module3_progress_summary():\n",
    "    print(\"📈 MODULE 3 PROGRESS SUMMARY\")\n",
    "    print(\"=\" * 40)\n",
    "    \n",
    "    capabilities = [\n",
    "        \"✅ Robust tool integration framework\",\n",
    "        \"✅ Database connectivity with safety checks\",\n",
    "        \"✅ Web API integration with auth & retries\",\n",
    "        \"✅ Secure file processing system\",\n",
    "        \"✅ Email communication capabilities\",\n",
    "        \"✅ Advanced tool management & orchestration\",\n",
    "        \"✅ Intelligent tool recommendation engine\",\n",
    "        \"✅ Complex workflow execution\"\n",
    "    ]\n",
    "    \n",
    "    print(\"\\n🔧 Tool Integration Capabilities:\")\n",
    "    for cap in capabilities:\n",
    "        print(f\"  {cap}\")\n",
    "    \n",
    "    # Get final tool statistics\n",
    "    final_stats = tool_manager.get_comprehensive_stats()\n",
    "    \n",
    "    print(f\"\\n📊 Final Tool System Statistics:\")\n",
    "    print(f\"  • Tools registered: {final_stats['total_tools']}\")\n",
    "    print(f\"  • Total executions: {final_stats['total_executions']}\")\n",
    "    print(f\"  • Tool categories: {len(final_stats['categories'])}\")\n",
    "    \n",
    "    # Show category breakdown\n",
    "    print(f\"\\n📁 Tool Categories:\")\n",
    "    for category, tools in final_stats['categories'].items():\n",
    "        print(f\"  • {category}: {len(tools)} tools\")\n",
    "    \n",
    "    # Calculate overall success rate\n",
    "    total_successes = 0\n",
    "    total_runs = 0\n",
    "    for tool_stats in final_stats['tool_stats'].values():\n",
    "        total_successes += tool_stats['successes']\n",
    "        total_runs += tool_stats['executions']\n",
    "    \n",
    "    overall_success_rate = (total_successes / total_runs * 100) if total_runs > 0 else 0\n",
    "    \n",
    "    print(f\"\\n🎯 Overall Performance:\")\n",
    "    print(f\"  • Success rate: {overall_success_rate:.1f}%\")\n",
    "    print(f\"  • Error handling: Robust with retries and fallbacks\")\n",
    "    print(f\"  • Security: Input validation and sandboxing\")\n",
    "    \n",
    "    print(f\"\\n🎯 Ready for Module 4: Planning and Goal Decomposition!\")\n",
    "    print(f\"\\n💡 Pro Tip: The tool integration system you built will be essential for executing complex plans!\")\n",
    "\n",
    "module3_progress_summary()"
   ]
  }\n",
 ],\n",
 \"metadata\": {\n",
  \"kernelspec\": {\n",
   \"display_name\": \"Python 3\",\n",
   \"language\": \"python\",\n",
   \"name\": \"python3\"\n",
  },\n",
  \"language_info\": {\n",
   \"codemirror_mode\": {\n",
    \"name\": \"ipython\",\n",
    \"version\": 3\n",
   },\n",
   \"file_extension\": \".py\",\n",
   \"mimetype\": \"text/x-python\",\n",
   \"name\": \"python\",\n",
   \"nbconvert_exporter\": \"python\",\n",
   \"pygments_lexer\": \"ipython3\",\n",
   \"version\": \"3.8.0\"\n",
  }\n }\n}